<?php

namespace App\Models;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Apirequests extends genClass
{
    protected $use_table = "apirequests";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "serverlink" => ["type" => "int", "value" => null],
        "rentallink" => ["type" => "int", "value" => null],
        "streamlink" => ["type" => "int", "value" => null],
        "eventname" => ["type" => "str", "value" => null],
        "attempts" => ["type" => "int", "value" => 0],
        "lastAttempt" => ["type" => "int", "value" => 0],
        "message" => ["type" => "str", "value" => null],
    ];
    public function getServerlink(): ?int
    {
        return $this->getField("serverlink");
    }
    public function getRentallink(): ?int
    {
        return $this->getField("rentallink");
    }
    public function getStreamlink(): ?int
    {
        return $this->getField("streamlink");
    }
    public function getEventname(): ?string
    {
        return $this->getField("eventname");
    }
    public function getAttempts(): ?int
    {
        return $this->getField("attempts");
    }
    public function getLastAttempt(): ?int
    {
        return $this->getField("lastAttempt");
    }
    public function getMessage(): ?string
    {
        return $this->getField("message");
    }
    /**
    * setServerlink
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setServerlink(?int $newvalue): array
    {
        return $this->updateField("serverlink", $newvalue);
    }
    /**
    * setRentallink
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setRentallink(?int $newvalue): array
    {
        return $this->updateField("rentallink", $newvalue);
    }
    /**
    * setStreamlink
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setStreamlink(?int $newvalue): array
    {
        return $this->updateField("streamlink", $newvalue);
    }
    /**
    * setEventname
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventname(?string $newvalue): array
    {
        return $this->updateField("eventname", $newvalue);
    }
    /**
    * setAttempts
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAttempts(?int $newvalue): array
    {
        return $this->updateField("attempts", $newvalue);
    }
    /**
    * setLastAttempt
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setLastAttempt(?int $newvalue): array
    {
        return $this->updateField("lastAttempt", $newvalue);
    }
    /**
    * setMessage
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setMessage(?string $newvalue): array
    {
        return $this->updateField("message", $newvalue);
    }
}
// please do not edit this file
