<?php

namespace App;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Avatar extends genClass
{
    protected $use_table = "avatar";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "avataruuid" => ["type" => "str", "value" => null],
        "avatarname" => ["type" => "str", "value" => null],
        "avatar_uid" => ["type" => "str", "value" => null],
    ];
    public function getAvataruuid(): ?string
    {
        return $this->getField("avataruuid");
    }
    public function getAvatarname(): ?string
    {
        return $this->getField("avatarname");
    }
    public function getAvatar_uid(): ?string
    {
        return $this->getField("avatar_uid");
    }
    /**
    * setAvataruuid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAvataruuid(?string $newvalue): array
    {
        return $this->updateField("avataruuid", $newvalue);
    }
    /**
    * setAvatarname
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAvatarname(?string $newvalue): array
    {
        return $this->updateField("avatarname", $newvalue);
    }
    /**
    * setAvatar_uid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAvatar_uid(?string $newvalue): array
    {
        return $this->updateField("avatar_uid", $newvalue);
    }
}
// please do not edit this file
