<?php

namespace App\Models;

use YAPF\Framework\DbObjects\GenClass\GenClass as GenClass;
use YAPF\Framework\Responses\DbObjects\UpdateReply as UpdateReply;
use YAPF\Framework\Responses\DbObjects\SingleLoadReply as SingleLoadReply;

// Do not edit this file, rerun gen.php to update!
class Botcommandq extends genClass
{
    protected $use_table = "botcommandq";
    // Data Design
    protected $fields = [
        "id",
        "command",
        "args",
        "unixtime",
    ];
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "command" => ["type" => "str", "value" => null],
        "args" => ["type" => "str", "value" => null],
        "unixtime" => ["type" => "int", "value" => null],
    ];
    // Setters
    /**
    * setCommand
    */
    public function setCommand(?string $newValue): UpdateReply
    {
        return $this->updateField("command", $newValue);
    }
    /**
    * setArgs
    */
    public function setArgs(?string $newValue): UpdateReply
    {
        return $this->updateField("args", $newValue);
    }
    /**
    * setUnixtime
    */
    public function setUnixtime(?int $newValue): UpdateReply
    {
        return $this->updateField("unixtime", $newValue);
    }
    // Getters
    public function getCommand(): ?string
    {
        return $this->getField("command");
    }
    public function getArgs(): ?string
    {
        return $this->getField("args");
    }
    public function getUnixtime(): ?int
    {
        return $this->getField("unixtime");
    }
    // Loaders
    public function loadByCommand(string $command): SingleLoadReply
    {
        return $this->loadByField(
            "command",
            $command
        );
    }
    public function loadByArgs(string $args): SingleLoadReply
    {
        return $this->loadByField(
            "args",
            $args
        );
    }
    public function loadByUnixtime(int $unixtime): SingleLoadReply
    {
        return $this->loadByField(
            "unixtime",
            $unixtime
        );
    }
}
// please do not edit this file
