<?php

namespace App\Models;

use YAPF\Framework\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Datatable extends genClass
{
    protected $use_table = "datatable";
    // Data Design
    protected $fields = [
        "id",
        "hideColZero",
        "col",
        "cols",
        "name",
        "dir",
    ];
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "hideColZero" => ["type" => "bool", "value" => 1],
        "col" => ["type" => "int", "value" => 0],
        "cols" => ["type" => "str", "value" => null],
        "name" => ["type" => "str", "value" => null],
        "dir" => ["type" => "str", "value" => "desc"],
    ];
    // Setters
    /**
    * setHideColZero
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setHideColZero(?bool $newvalue): array
    {
        return $this->updateField("hideColZero", $newvalue);
    }
    /**
    * setCol
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setCol(?int $newvalue): array
    {
        return $this->updateField("col", $newvalue);
    }
    /**
    * setCols
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setCols(?string $newvalue): array
    {
        return $this->updateField("cols", $newvalue);
    }
    /**
    * setName
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setName(?string $newvalue): array
    {
        return $this->updateField("name", $newvalue);
    }
    /**
    * setDir
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setDir(?string $newvalue): array
    {
        return $this->updateField("dir", $newvalue);
    }
    // Getters
    public function getHideColZero(): ?bool
    {
        return $this->getField("hideColZero");
    }
    public function getCol(): ?int
    {
        return $this->getField("col");
    }
    public function getCols(): ?string
    {
        return $this->getField("cols");
    }
    public function getName(): ?string
    {
        return $this->getField("name");
    }
    public function getDir(): ?string
    {
        return $this->getField("dir");
    }
    // Loaders
    public function loadByHideColZero(bool $hideColZero): bool
    {
        return $this->loadByField(
            "hideColZero",
            $hideColZero
        );
    }
    public function loadByCol(int $col): bool
    {
        return $this->loadByField(
            "col",
            $col
        );
    }
    public function loadByCols(string $cols): bool
    {
        return $this->loadByField(
            "cols",
            $cols
        );
    }
    public function loadByName(string $name): bool
    {
        return $this->loadByField(
            "name",
            $name
        );
    }
    public function loadByDir(string $dir): bool
    {
        return $this->loadByField(
            "dir",
            $dir
        );
    }
}
// please do not edit this file
