<?php

namespace App\Models;

use YAPF\Framework\DbObjects\GenClass\GenClass as GenClass;
use YAPF\Framework\Responses\DbObjects\UpdateReply as UpdateReply;
use YAPF\Framework\Responses\DbObjects\SingleLoadReply as SingleLoadReply;
use App\Models\Set\AvatarSet as TestAvatar;

// Do not edit this file, rerun gen.php to update!
class Message extends genClass
{
    protected $use_table = "message";
    // Data Design
    protected $fields = [
        "id",
        "avatarLink",
        "message",
    ];
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "avatarLink" => ["type" => "int", "value" => null],
        "message" => ["type" => "str", "value" => null],
    ];
    // Setters
    /**
    * setAvatarLink
    */
    public function setAvatarLink(?int $newValue): UpdateReply
    {
        return $this->updateField("avatarLink", $newValue);
    }
    /**
    * setMessage
    */
    public function setMessage(?string $newValue): UpdateReply
    {
        return $this->updateField("message", $newValue);
    }
    // Getters
    public function getAvatarLink(): ?int
    {
        return $this->getField("avatarLink");
    }
    public function getMessage(): ?string
    {
        return $this->getField("message");
    }
    // Loaders
    public function loadByAvatarLink(int $avatarLink): SingleLoadReply
    {
        return $this->loadByField(
            "avatarLink",
            $avatarLink
        );
    }
    public function loadByMessage(string $message): SingleLoadReply
    {
        return $this->loadByField(
            "message",
            $message
        );
    }
    public function relatedAvatar(?array $limitFields = null): TestAvatar
    {
        $ids = [$this->getAvatarLink()];
        $collection = new TestAvatar();
        if ($limitFields !== null) {
            $collection->limitFields($limitFields);
        }
        $collection->loadFromIds($ids);
        return $collection;
    }
}
// please do not edit this file
