<?php

namespace App\Models;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Message extends genClass
{
    protected $use_table = "message";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "avatarlink" => ["type" => "int", "value" => null],
        "message" => ["type" => "str", "value" => null],
    ];
    public function getAvatarlink(): ?int
    {
        return $this->getField("avatarlink");
    }
    public function getMessage(): ?string
    {
        return $this->getField("message");
    }
    /**
    * setAvatarlink
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAvatarlink(?int $newvalue): array
    {
        return $this->updateField("avatarlink", $newvalue);
    }
    /**
    * setMessage
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setMessage(?string $newvalue): array
    {
        return $this->updateField("message", $newvalue);
    }
}
// please do not edit this file
