<?php

namespace App\Models;

use YAPF\Framework\DbObjects\GenClass\GenClass as GenClass;
use YAPF\Framework\Responses\DbObjects\UpdateReply as UpdateReply;
use YAPF\Framework\Responses\DbObjects\SingleLoadReply as SingleLoadReply;
use App\Models\Set\NotecardmailSet as TestNotecardmail;
use App\Models\Set\PackageSet as TestPackage;
use App\Models\Set\NoticeSet as TestNotice;

// Do not edit this file, rerun gen.php to update!
class Noticenotecard extends genClass
{
    protected $use_table = "noticenotecard";
    // Data Design
    protected $fields = [
        "id",
        "name",
        "missing",
    ];
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "name" => ["type" => "str", "value" => null],
        "missing" => ["type" => "bool", "value" => 0],
    ];
    // Setters
    /**
    * setName
    */
    public function setName(?string $newValue): UpdateReply
    {
        return $this->updateField("name", $newValue);
    }
    /**
    * setMissing
    */
    public function setMissing(?bool $newValue): UpdateReply
    {
        return $this->updateField("missing", $newValue);
    }
    // Getters
    public function getName(): ?string
    {
        return $this->getField("name");
    }
    public function getMissing(): ?bool
    {
        return $this->getField("missing");
    }
    // Loaders
    public function loadByName(string $name): SingleLoadReply
    {
        return $this->loadByField(
            "name",
            $name
        );
    }
    public function loadByMissing(bool $missing): SingleLoadReply
    {
        return $this->loadByField(
            "missing",
            $missing
        );
    }
    public function relatedNotecardmail(?array $limitFields = null): TestNotecardmail
    {
        $ids = [$this->getId()];
        $collection = new TestNotecardmail();
        if ($limitFields !== null) {
            $collection->limitFields($limitFields);
        }
        $collection->loadFromNoticenotecardLinks($ids);
        return $collection;
    }
    public function relatedPackage(?array $limitFields = null): TestPackage
    {
        $ids = [$this->getId()];
        $collection = new TestPackage();
        if ($limitFields !== null) {
            $collection->limitFields($limitFields);
        }
        $collection->loadFromWelcomeNotecardLinks($ids);
        return $collection;
    }
    public function relatedNotice(?array $limitFields = null): TestNotice
    {
        $ids = [$this->getId()];
        $collection = new TestNotice();
        if ($limitFields !== null) {
            $collection->limitFields($limitFields);
        }
        $collection->loadFromNoticeNotecardLinks($ids);
        return $collection;
    }
}
// please do not edit this file
