<?php

namespace App;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Noticenotecard extends genClass
{
    protected $use_table = "noticenotecard";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "name" => ["type" => "str", "value" => null],
        "missing" => ["type" => "bool", "value" => 0],
    ];
    public function getName(): ?string
    {
        return $this->getField("name");
    }
    public function getMissing(): ?bool
    {
        return $this->getField("missing");
    }
    /**
    * setName
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setName(?string $newvalue): array
    {
        return $this->updateField("name", $newvalue);
    }
    /**
    * setMissing
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setMissing(?bool $newvalue): array
    {
        return $this->updateField("missing", $newvalue);
    }
}
// please do not edit this file
