<?php

namespace App\Models;

use YAPF\Framework\DbObjects\GenClass\GenClass as GenClass;
use YAPF\Framework\Responses\DbObjects\UpdateReply as UpdateReply;
use YAPF\Framework\Responses\DbObjects\SingleLoadReply as SingleLoadReply;
use App\Models\Sets\NoticenotecardSet as NoticenotecardSet;
use App\Models\Sets\ServertypesSet as ServertypesSet;
use App\Models\Sets\TemplateSet as TemplateSet;
use App\Models\Sets\RentalSet as RentalSet;
use App\Models\Sets\StreamSet as StreamSet;
use App\Models\Sets\TransactionsSet as TransactionsSet;
use App\Models\Sets\TreevenderpackagesSet as TreevenderpackagesSet;

// Do not edit this file, rerun gen.php to update!
class Package extends genClass
{
    protected $use_table = "package";
    // Data Design
    protected $fields = [
        "id",
        "packageUid",
        "name",
        "autodj",
        "autodjSize",
        "listeners",
        "bitrate",
        "templateLink",
        "servertypeLink",
        "cost",
        "days",
        "textureSoldout",
        "textureInstockSmall",
        "textureInstockSelected",
        "apiTemplate",
        "welcomeNotecardLink",
        "setupNotecardLink",
        "enableGroupInvite",
    ];
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "packageUid" => ["type" => "str", "value" => null],
        "name" => ["type" => "str", "value" => null],
        "autodj" => ["type" => "bool", "value" => 0],
        "autodjSize" => ["type" => "str", "value" => null],
        "listeners" => ["type" => "int", "value" => null],
        "bitrate" => ["type" => "int", "value" => null],
        "templateLink" => ["type" => "int", "value" => null],
        "servertypeLink" => ["type" => "int", "value" => 1],
        "cost" => ["type" => "int", "value" => null],
        "days" => ["type" => "int", "value" => null],
        "textureSoldout" => ["type" => "str", "value" => null],
        "textureInstockSmall" => ["type" => "str", "value" => null],
        "textureInstockSelected" => ["type" => "str", "value" => null],
        "apiTemplate" => ["type" => "str", "value" => null],
        "welcomeNotecardLink" => ["type" => "int", "value" => 1],
        "setupNotecardLink" => ["type" => "int", "value" => 1],
        "enableGroupInvite" => ["type" => "bool", "value" => 1],
    ];
    // Setters
    /**
    * setPackageUid
    */
    public function setPackageUid(?string $newValue): UpdateReply
    {
        return $this->updateField("packageUid", $newValue);
    }
    /**
    * setName
    */
    public function setName(?string $newValue): UpdateReply
    {
        return $this->updateField("name", $newValue);
    }
    /**
    * setAutodj
    */
    public function setAutodj(?bool $newValue): UpdateReply
    {
        return $this->updateField("autodj", $newValue);
    }
    /**
    * setAutodjSize
    */
    public function setAutodjSize(?string $newValue): UpdateReply
    {
        return $this->updateField("autodjSize", $newValue);
    }
    /**
    * setListeners
    */
    public function setListeners(?int $newValue): UpdateReply
    {
        return $this->updateField("listeners", $newValue);
    }
    /**
    * setBitrate
    */
    public function setBitrate(?int $newValue): UpdateReply
    {
        return $this->updateField("bitrate", $newValue);
    }
    /**
    * setTemplateLink
    */
    public function setTemplateLink(?int $newValue): UpdateReply
    {
        return $this->updateField("templateLink", $newValue);
    }
    /**
    * setServertypeLink
    */
    public function setServertypeLink(?int $newValue): UpdateReply
    {
        return $this->updateField("servertypeLink", $newValue);
    }
    /**
    * setCost
    */
    public function setCost(?int $newValue): UpdateReply
    {
        return $this->updateField("cost", $newValue);
    }
    /**
    * setDays
    */
    public function setDays(?int $newValue): UpdateReply
    {
        return $this->updateField("days", $newValue);
    }
    /**
    * setTextureSoldout
    */
    public function setTextureSoldout(?string $newValue): UpdateReply
    {
        return $this->updateField("textureSoldout", $newValue);
    }
    /**
    * setTextureInstockSmall
    */
    public function setTextureInstockSmall(?string $newValue): UpdateReply
    {
        return $this->updateField("textureInstockSmall", $newValue);
    }
    /**
    * setTextureInstockSelected
    */
    public function setTextureInstockSelected(?string $newValue): UpdateReply
    {
        return $this->updateField("textureInstockSelected", $newValue);
    }
    /**
    * setApiTemplate
    */
    public function setApiTemplate(?string $newValue): UpdateReply
    {
        return $this->updateField("apiTemplate", $newValue);
    }
    /**
    * setWelcomeNotecardLink
    */
    public function setWelcomeNotecardLink(?int $newValue): UpdateReply
    {
        return $this->updateField("welcomeNotecardLink", $newValue);
    }
    /**
    * setSetupNotecardLink
    */
    public function setSetupNotecardLink(?int $newValue): UpdateReply
    {
        return $this->updateField("setupNotecardLink", $newValue);
    }
    /**
    * setEnableGroupInvite
    */
    public function setEnableGroupInvite(?bool $newValue): UpdateReply
    {
        return $this->updateField("enableGroupInvite", $newValue);
    }
    // Getters
    public function getPackageUid(): ?string
    {
        return $this->getField("packageUid");
    }
    public function getName(): ?string
    {
        return $this->getField("name");
    }
    public function getAutodj(): ?bool
    {
        return $this->getField("autodj");
    }
    public function getAutodjSize(): ?string
    {
        return $this->getField("autodjSize");
    }
    public function getListeners(): ?int
    {
        return $this->getField("listeners");
    }
    public function getBitrate(): ?int
    {
        return $this->getField("bitrate");
    }
    public function getTemplateLink(): ?int
    {
        return $this->getField("templateLink");
    }
    public function getServertypeLink(): ?int
    {
        return $this->getField("servertypeLink");
    }
    public function getCost(): ?int
    {
        return $this->getField("cost");
    }
    public function getDays(): ?int
    {
        return $this->getField("days");
    }
    public function getTextureSoldout(): ?string
    {
        return $this->getField("textureSoldout");
    }
    public function getTextureInstockSmall(): ?string
    {
        return $this->getField("textureInstockSmall");
    }
    public function getTextureInstockSelected(): ?string
    {
        return $this->getField("textureInstockSelected");
    }
    public function getApiTemplate(): ?string
    {
        return $this->getField("apiTemplate");
    }
    public function getWelcomeNotecardLink(): ?int
    {
        return $this->getField("welcomeNotecardLink");
    }
    public function getSetupNotecardLink(): ?int
    {
        return $this->getField("setupNotecardLink");
    }
    public function getEnableGroupInvite(): ?bool
    {
        return $this->getField("enableGroupInvite");
    }
    // Loaders
    public function loadByPackageUid(string $packageUid): SingleLoadReply
    {
        return $this->loadByField(
            "packageUid",
            $packageUid
        );
    }
    public function loadByName(string $name): SingleLoadReply
    {
        return $this->loadByField(
            "name",
            $name
        );
    }
    public function loadByAutodj(bool $autodj): SingleLoadReply
    {
        return $this->loadByField(
            "autodj",
            $autodj
        );
    }
    public function loadByAutodjSize(string $autodjSize): SingleLoadReply
    {
        return $this->loadByField(
            "autodjSize",
            $autodjSize
        );
    }
    public function loadByListeners(int $listeners): SingleLoadReply
    {
        return $this->loadByField(
            "listeners",
            $listeners
        );
    }
    public function loadByBitrate(int $bitrate): SingleLoadReply
    {
        return $this->loadByField(
            "bitrate",
            $bitrate
        );
    }
    public function loadByTemplateLink(int $templateLink): SingleLoadReply
    {
        return $this->loadByField(
            "templateLink",
            $templateLink
        );
    }
    public function loadByServertypeLink(int $servertypeLink): SingleLoadReply
    {
        return $this->loadByField(
            "servertypeLink",
            $servertypeLink
        );
    }
    public function loadByCost(int $cost): SingleLoadReply
    {
        return $this->loadByField(
            "cost",
            $cost
        );
    }
    public function loadByDays(int $days): SingleLoadReply
    {
        return $this->loadByField(
            "days",
            $days
        );
    }
    public function loadByTextureSoldout(string $textureSoldout): SingleLoadReply
    {
        return $this->loadByField(
            "textureSoldout",
            $textureSoldout
        );
    }
    public function loadByTextureInstockSmall(string $textureInstockSmall): SingleLoadReply
    {
        return $this->loadByField(
            "textureInstockSmall",
            $textureInstockSmall
        );
    }
    public function loadByTextureInstockSelected(string $textureInstockSelected): SingleLoadReply
    {
        return $this->loadByField(
            "textureInstockSelected",
            $textureInstockSelected
        );
    }
    public function loadByApiTemplate(string $apiTemplate): SingleLoadReply
    {
        return $this->loadByField(
            "apiTemplate",
            $apiTemplate
        );
    }
    public function loadByWelcomeNotecardLink(int $welcomeNotecardLink): SingleLoadReply
    {
        return $this->loadByField(
            "welcomeNotecardLink",
            $welcomeNotecardLink
        );
    }
    public function loadBySetupNotecardLink(int $setupNotecardLink): SingleLoadReply
    {
        return $this->loadByField(
            "setupNotecardLink",
            $setupNotecardLink
        );
    }
    public function loadByEnableGroupInvite(bool $enableGroupInvite): SingleLoadReply
    {
        return $this->loadByField(
            "enableGroupInvite",
            $enableGroupInvite
        );
    }
    public function relatedNoticenotecard(): NoticenotecardSet
    {
        $ids = [$this->getWelcomeNotecardLink()];
        $collection = new NoticenotecardSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
    public function relatedServertypes(): ServertypesSet
    {
        $ids = [$this->getServertypeLink()];
        $collection = new ServertypesSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
    public function relatedTemplate(): TemplateSet
    {
        $ids = [$this->getTemplateLink()];
        $collection = new TemplateSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
    public function relatedRental(): RentalSet
    {
        $ids = [$this->getId()];
        $collection = new RentalSet();
        $collection->loadFromPackageLinks($ids);
        return $collection;
    }
    public function relatedStream(): StreamSet
    {
        $ids = [$this->getId()];
        $collection = new StreamSet();
        $collection->loadFromPackageLinks($ids);
        return $collection;
    }
    public function relatedTransactions(): TransactionsSet
    {
        $ids = [$this->getId()];
        $collection = new TransactionsSet();
        $collection->loadFromPackageLinks($ids);
        return $collection;
    }
    public function relatedTreevenderpackages(): TreevenderpackagesSet
    {
        $ids = [$this->getId()];
        $collection = new TreevenderpackagesSet();
        $collection->loadFromPackageLinks($ids);
        return $collection;
    }
}
// please do not edit this file
