<?php

namespace App\Models;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Reseller extends genClass
{
    protected $use_table = "reseller";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "avatarlink" => ["type" => "int", "value" => null],
        "allowed" => ["type" => "bool", "value" => 0],
        "rate" => ["type" => "int", "value" => 0],
    ];
    public function getAvatarlink(): ?int
    {
        return $this->getField("avatarlink");
    }
    public function getAllowed(): ?bool
    {
        return $this->getField("allowed");
    }
    public function getRate(): ?int
    {
        return $this->getField("rate");
    }
    /**
    * setAvatarlink
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAvatarlink(?int $newvalue): array
    {
        return $this->updateField("avatarlink", $newvalue);
    }
    /**
    * setAllowed
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAllowed(?bool $newvalue): array
    {
        return $this->updateField("allowed", $newvalue);
    }
    /**
    * setRate
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setRate(?int $newvalue): array
    {
        return $this->updateField("rate", $newvalue);
    }
}
// please do not edit this file
