<?php

namespace App\Models;

use YAPF\Framework\DbObjects\GenClass\GenClass as GenClass;
use App\Models\Sets\AvatarSet as AvatarSet;
use App\Models\Sets\TransactionsSet as TransactionsSet;

// Do not edit this file, rerun gen.php to update!
class Reseller extends genClass
{
    protected $use_table = "reseller";
    // Data Design
    protected $fields = [
        "id",
        "avatarLink",
        "allowed",
        "rate",
    ];
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "avatarLink" => ["type" => "int", "value" => null],
        "allowed" => ["type" => "bool", "value" => 0],
        "rate" => ["type" => "int", "value" => 0],
    ];
    // Setters
    /**
    * setAvatarLink
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAvatarLink(?int $newvalue): array
    {
        return $this->updateField("avatarLink", $newvalue);
    }
    /**
    * setAllowed
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAllowed(?bool $newvalue): array
    {
        return $this->updateField("allowed", $newvalue);
    }
    /**
    * setRate
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setRate(?int $newvalue): array
    {
        return $this->updateField("rate", $newvalue);
    }
    // Getters
    public function getAvatarLink(): ?int
    {
        return $this->getField("avatarLink");
    }
    public function getAllowed(): ?bool
    {
        return $this->getField("allowed");
    }
    public function getRate(): ?int
    {
        return $this->getField("rate");
    }
    // Loaders
    public function loadByAvatarLink(int $avatarLink): bool
    {
        return $this->loadByField(
            "avatarLink",
            $avatarLink
        );
    }
    public function loadByAllowed(bool $allowed): bool
    {
        return $this->loadByField(
            "allowed",
            $allowed
        );
    }
    public function loadByRate(int $rate): bool
    {
        return $this->loadByField(
            "rate",
            $rate
        );
    }
    public function relatedAvatar(): AvatarSet
    {
        $ids = [$this->getAvatarLink()];
        $collection = new AvatarSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
    public function relatedTransactions(): TransactionsSet
    {
        $ids = [$this->getId()];
        $collection = new TransactionsSet();
        $collection->loadFromResellerLinks($ids);
        return $collection;
    }
}
// please do not edit this file
