<?php

namespace App\Models;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Server extends genClass
{
    protected $use_table = "server";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "domain" => ["type" => "str", "value" => null],
        "controlPanelURL" => ["type" => "str", "value" => null],
        "apiLink" => ["type" => "int", "value" => 1],
        "apiURL" => ["type" => "str", "value" => null],
        "apiUsername" => ["type" => "str", "value" => null],
        "apiPassword" => ["type" => "str", "value" => null],
        "apiServerStatus" => ["type" => "bool", "value" => 0],
        "apiSyncAccounts" => ["type" => "bool", "value" => 0],
        "optPasswordReset" => ["type" => "bool", "value" => 0],
        "optAutodjNext" => ["type" => "bool", "value" => 0],
        "optToggleAutodj" => ["type" => "bool", "value" => 0],
        "optToggleStatus" => ["type" => "bool", "value" => 0],
        "eventEnableStart" => ["type" => "bool", "value" => 0],
        "eventStartSyncUsername" => ["type" => "bool", "value" => 0],
        "eventEnableRenew" => ["type" => "bool", "value" => 0],
        "eventDisableExpire" => ["type" => "bool", "value" => 0],
        "eventDisableRevoke" => ["type" => "bool", "value" => 0],
        "eventRevokeResetUsername" => ["type" => "bool", "value" => 0],
        "eventResetPasswordRevoke" => ["type" => "bool", "value" => 0],
        "eventClearDjs" => ["type" => "bool", "value" => 0],
        "eventRecreateRevoke" => ["type" => "bool", "value" => 0],
        "lastApiSync" => ["type" => "int", "value" => 0],
        "eventCreateStream" => ["type" => "bool", "value" => 0],
        "eventUpdateStream" => ["type" => "bool", "value" => 0],
    ];
    public function getDomain(): ?string
    {
        return $this->getField("domain");
    }
    public function getControlPanelURL(): ?string
    {
        return $this->getField("controlPanelURL");
    }
    public function getApiLink(): ?int
    {
        return $this->getField("apiLink");
    }
    public function getApiURL(): ?string
    {
        return $this->getField("apiURL");
    }
    public function getApiUsername(): ?string
    {
        return $this->getField("apiUsername");
    }
    public function getApiPassword(): ?string
    {
        return $this->getField("apiPassword");
    }
    public function getApiServerStatus(): ?bool
    {
        return $this->getField("apiServerStatus");
    }
    public function getApiSyncAccounts(): ?bool
    {
        return $this->getField("apiSyncAccounts");
    }
    public function getOptPasswordReset(): ?bool
    {
        return $this->getField("optPasswordReset");
    }
    public function getOptAutodjNext(): ?bool
    {
        return $this->getField("optAutodjNext");
    }
    public function getOptToggleAutodj(): ?bool
    {
        return $this->getField("optToggleAutodj");
    }
    public function getOptToggleStatus(): ?bool
    {
        return $this->getField("optToggleStatus");
    }
    public function getEventEnableStart(): ?bool
    {
        return $this->getField("eventEnableStart");
    }
    public function getEventStartSyncUsername(): ?bool
    {
        return $this->getField("eventStartSyncUsername");
    }
    public function getEventEnableRenew(): ?bool
    {
        return $this->getField("eventEnableRenew");
    }
    public function getEventDisableExpire(): ?bool
    {
        return $this->getField("eventDisableExpire");
    }
    public function getEventDisableRevoke(): ?bool
    {
        return $this->getField("eventDisableRevoke");
    }
    public function getEventRevokeResetUsername(): ?bool
    {
        return $this->getField("eventRevokeResetUsername");
    }
    public function getEventResetPasswordRevoke(): ?bool
    {
        return $this->getField("eventResetPasswordRevoke");
    }
    public function getEventClearDjs(): ?bool
    {
        return $this->getField("eventClearDjs");
    }
    public function getEventRecreateRevoke(): ?bool
    {
        return $this->getField("eventRecreateRevoke");
    }
    public function getLastApiSync(): ?int
    {
        return $this->getField("lastApiSync");
    }
    public function getEventCreateStream(): ?bool
    {
        return $this->getField("eventCreateStream");
    }
    public function getEventUpdateStream(): ?bool
    {
        return $this->getField("eventUpdateStream");
    }
    /**
    * setDomain
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setDomain(?string $newvalue): array
    {
        return $this->updateField("domain", $newvalue);
    }
    /**
    * setControlPanelURL
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setControlPanelURL(?string $newvalue): array
    {
        return $this->updateField("controlPanelURL", $newvalue);
    }
    /**
    * setApiLink
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setApiLink(?int $newvalue): array
    {
        return $this->updateField("apiLink", $newvalue);
    }
    /**
    * setApiURL
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setApiURL(?string $newvalue): array
    {
        return $this->updateField("apiURL", $newvalue);
    }
    /**
    * setApiUsername
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setApiUsername(?string $newvalue): array
    {
        return $this->updateField("apiUsername", $newvalue);
    }
    /**
    * setApiPassword
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setApiPassword(?string $newvalue): array
    {
        return $this->updateField("apiPassword", $newvalue);
    }
    /**
    * setApiServerStatus
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setApiServerStatus(?bool $newvalue): array
    {
        return $this->updateField("apiServerStatus", $newvalue);
    }
    /**
    * setApiSyncAccounts
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setApiSyncAccounts(?bool $newvalue): array
    {
        return $this->updateField("apiSyncAccounts", $newvalue);
    }
    /**
    * setOptPasswordReset
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setOptPasswordReset(?bool $newvalue): array
    {
        return $this->updateField("optPasswordReset", $newvalue);
    }
    /**
    * setOptAutodjNext
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setOptAutodjNext(?bool $newvalue): array
    {
        return $this->updateField("optAutodjNext", $newvalue);
    }
    /**
    * setOptToggleAutodj
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setOptToggleAutodj(?bool $newvalue): array
    {
        return $this->updateField("optToggleAutodj", $newvalue);
    }
    /**
    * setOptToggleStatus
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setOptToggleStatus(?bool $newvalue): array
    {
        return $this->updateField("optToggleStatus", $newvalue);
    }
    /**
    * setEventEnableStart
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventEnableStart(?bool $newvalue): array
    {
        return $this->updateField("eventEnableStart", $newvalue);
    }
    /**
    * setEventStartSyncUsername
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventStartSyncUsername(?bool $newvalue): array
    {
        return $this->updateField("eventStartSyncUsername", $newvalue);
    }
    /**
    * setEventEnableRenew
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventEnableRenew(?bool $newvalue): array
    {
        return $this->updateField("eventEnableRenew", $newvalue);
    }
    /**
    * setEventDisableExpire
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventDisableExpire(?bool $newvalue): array
    {
        return $this->updateField("eventDisableExpire", $newvalue);
    }
    /**
    * setEventDisableRevoke
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventDisableRevoke(?bool $newvalue): array
    {
        return $this->updateField("eventDisableRevoke", $newvalue);
    }
    /**
    * setEventRevokeResetUsername
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventRevokeResetUsername(?bool $newvalue): array
    {
        return $this->updateField("eventRevokeResetUsername", $newvalue);
    }
    /**
    * setEventResetPasswordRevoke
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventResetPasswordRevoke(?bool $newvalue): array
    {
        return $this->updateField("eventResetPasswordRevoke", $newvalue);
    }
    /**
    * setEventClearDjs
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventClearDjs(?bool $newvalue): array
    {
        return $this->updateField("eventClearDjs", $newvalue);
    }
    /**
    * setEventRecreateRevoke
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventRecreateRevoke(?bool $newvalue): array
    {
        return $this->updateField("eventRecreateRevoke", $newvalue);
    }
    /**
    * setLastApiSync
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setLastApiSync(?int $newvalue): array
    {
        return $this->updateField("lastApiSync", $newvalue);
    }
    /**
    * setEventCreateStream
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventCreateStream(?bool $newvalue): array
    {
        return $this->updateField("eventCreateStream", $newvalue);
    }
    /**
    * setEventUpdateStream
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setEventUpdateStream(?bool $newvalue): array
    {
        return $this->updateField("eventUpdateStream", $newvalue);
    }
}
// please do not edit this file
