<?php

namespace App;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Textureconfig extends genClass
{
    protected $use_table = "textureconfig";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "name" => ["type" => "str", "value" => null],
        "offline" => ["type" => "str", "value" => null],
        "wait_owner" => ["type" => "str", "value" => null],
        "stock_levels" => ["type" => "str", "value" => null],
        "make_payment" => ["type" => "str", "value" => null],
        "inuse" => ["type" => "str", "value" => null],
        "renew_here" => ["type" => "str", "value" => null],
        "treevend_waiting" => ["type" => "str", "value" => null],
        "proxyrenew" => ["type" => "str", "value" => null],
        "getting_details" => ["type" => "str", "value" => null],
        "request_details" => ["type" => "str", "value" => null],
    ];
    public function getName(): ?string
    {
        return $this->getField("name");
    }
    public function getOffline(): ?string
    {
        return $this->getField("offline");
    }
    public function getWait_owner(): ?string
    {
        return $this->getField("wait_owner");
    }
    public function getStock_levels(): ?string
    {
        return $this->getField("stock_levels");
    }
    public function getMake_payment(): ?string
    {
        return $this->getField("make_payment");
    }
    public function getInuse(): ?string
    {
        return $this->getField("inuse");
    }
    public function getRenew_here(): ?string
    {
        return $this->getField("renew_here");
    }
    public function getTreevend_waiting(): ?string
    {
        return $this->getField("treevend_waiting");
    }
    public function getProxyrenew(): ?string
    {
        return $this->getField("proxyrenew");
    }
    public function getGetting_details(): ?string
    {
        return $this->getField("getting_details");
    }
    public function getRequest_details(): ?string
    {
        return $this->getField("request_details");
    }
    /**
    * setName
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setName(?string $newvalue): array
    {
        return $this->updateField("name", $newvalue);
    }
    /**
    * setOffline
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setOffline(?string $newvalue): array
    {
        return $this->updateField("offline", $newvalue);
    }
    /**
    * setWait_owner
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setWait_owner(?string $newvalue): array
    {
        return $this->updateField("wait_owner", $newvalue);
    }
    /**
    * setStock_levels
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setStock_levels(?string $newvalue): array
    {
        return $this->updateField("stock_levels", $newvalue);
    }
    /**
    * setMake_payment
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setMake_payment(?string $newvalue): array
    {
        return $this->updateField("make_payment", $newvalue);
    }
    /**
    * setInuse
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setInuse(?string $newvalue): array
    {
        return $this->updateField("inuse", $newvalue);
    }
    /**
    * setRenew_here
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setRenew_here(?string $newvalue): array
    {
        return $this->updateField("renew_here", $newvalue);
    }
    /**
    * setTreevend_waiting
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setTreevend_waiting(?string $newvalue): array
    {
        return $this->updateField("treevend_waiting", $newvalue);
    }
    /**
    * setProxyrenew
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setProxyrenew(?string $newvalue): array
    {
        return $this->updateField("proxyrenew", $newvalue);
    }
    /**
    * setGetting_details
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setGetting_details(?string $newvalue): array
    {
        return $this->updateField("getting_details", $newvalue);
    }
    /**
    * setRequest_details
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setRequest_details(?string $newvalue): array
    {
        return $this->updateField("request_details", $newvalue);
    }
}
// please do not edit this file
