<?php

namespace App\Models;

use YAPF\Framework\DbObjects\GenClass\GenClass as GenClass;
use YAPF\Framework\Responses\DbObjects\UpdateReply as UpdateReply;
use YAPF\Framework\Responses\DbObjects\SingleLoadReply as SingleLoadReply;

// Do not edit this file, rerun gen.php to update!
class Textureconfig extends genClass
{
    protected $use_table = "textureconfig";
    // Data Design
    protected $fields = [
        "id",
        "name",
        "offline",
        "waitOwner",
        "stockLevels",
        "makePayment",
        "inUse",
        "renewHere",
        "proxyRenew",
        "gettingDetails",
        "requestDetails",
    ];
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "name" => ["type" => "str", "value" => null],
        "offline" => ["type" => "str", "value" => null],
        "waitOwner" => ["type" => "str", "value" => null],
        "stockLevels" => ["type" => "str", "value" => null],
        "makePayment" => ["type" => "str", "value" => null],
        "inUse" => ["type" => "str", "value" => null],
        "renewHere" => ["type" => "str", "value" => null],
        "proxyRenew" => ["type" => "str", "value" => null],
        "gettingDetails" => ["type" => "str", "value" => null],
        "requestDetails" => ["type" => "str", "value" => null],
    ];
    // Setters
    /**
    * setName
    */
    public function setName(?string $newValue): UpdateReply
    {
        return $this->updateField("name", $newValue);
    }
    /**
    * setOffline
    */
    public function setOffline(?string $newValue): UpdateReply
    {
        return $this->updateField("offline", $newValue);
    }
    /**
    * setWaitOwner
    */
    public function setWaitOwner(?string $newValue): UpdateReply
    {
        return $this->updateField("waitOwner", $newValue);
    }
    /**
    * setStockLevels
    */
    public function setStockLevels(?string $newValue): UpdateReply
    {
        return $this->updateField("stockLevels", $newValue);
    }
    /**
    * setMakePayment
    */
    public function setMakePayment(?string $newValue): UpdateReply
    {
        return $this->updateField("makePayment", $newValue);
    }
    /**
    * setInUse
    */
    public function setInUse(?string $newValue): UpdateReply
    {
        return $this->updateField("inUse", $newValue);
    }
    /**
    * setRenewHere
    */
    public function setRenewHere(?string $newValue): UpdateReply
    {
        return $this->updateField("renewHere", $newValue);
    }
    /**
    * setProxyRenew
    */
    public function setProxyRenew(?string $newValue): UpdateReply
    {
        return $this->updateField("proxyRenew", $newValue);
    }
    /**
    * setGettingDetails
    */
    public function setGettingDetails(?string $newValue): UpdateReply
    {
        return $this->updateField("gettingDetails", $newValue);
    }
    /**
    * setRequestDetails
    */
    public function setRequestDetails(?string $newValue): UpdateReply
    {
        return $this->updateField("requestDetails", $newValue);
    }
    // Getters
    public function getName(): ?string
    {
        return $this->getField("name");
    }
    public function getOffline(): ?string
    {
        return $this->getField("offline");
    }
    public function getWaitOwner(): ?string
    {
        return $this->getField("waitOwner");
    }
    public function getStockLevels(): ?string
    {
        return $this->getField("stockLevels");
    }
    public function getMakePayment(): ?string
    {
        return $this->getField("makePayment");
    }
    public function getInUse(): ?string
    {
        return $this->getField("inUse");
    }
    public function getRenewHere(): ?string
    {
        return $this->getField("renewHere");
    }
    public function getProxyRenew(): ?string
    {
        return $this->getField("proxyRenew");
    }
    public function getGettingDetails(): ?string
    {
        return $this->getField("gettingDetails");
    }
    public function getRequestDetails(): ?string
    {
        return $this->getField("requestDetails");
    }
    // Loaders
    public function loadByName(string $name): SingleLoadReply
    {
        return $this->loadByField(
            "name",
            $name
        );
    }
    public function loadByOffline(string $offline): SingleLoadReply
    {
        return $this->loadByField(
            "offline",
            $offline
        );
    }
    public function loadByWaitOwner(string $waitOwner): SingleLoadReply
    {
        return $this->loadByField(
            "waitOwner",
            $waitOwner
        );
    }
    public function loadByStockLevels(string $stockLevels): SingleLoadReply
    {
        return $this->loadByField(
            "stockLevels",
            $stockLevels
        );
    }
    public function loadByMakePayment(string $makePayment): SingleLoadReply
    {
        return $this->loadByField(
            "makePayment",
            $makePayment
        );
    }
    public function loadByInUse(string $inUse): SingleLoadReply
    {
        return $this->loadByField(
            "inUse",
            $inUse
        );
    }
    public function loadByRenewHere(string $renewHere): SingleLoadReply
    {
        return $this->loadByField(
            "renewHere",
            $renewHere
        );
    }
    public function loadByProxyRenew(string $proxyRenew): SingleLoadReply
    {
        return $this->loadByField(
            "proxyRenew",
            $proxyRenew
        );
    }
    public function loadByGettingDetails(string $gettingDetails): SingleLoadReply
    {
        return $this->loadByField(
            "gettingDetails",
            $gettingDetails
        );
    }
    public function loadByRequestDetails(string $requestDetails): SingleLoadReply
    {
        return $this->loadByField(
            "requestDetails",
            $requestDetails
        );
    }
}
// please do not edit this file
