<?php

namespace App\Models\Sets;

use YAPF\Framework\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use App\Models\Datatable as Datatable;

// Do not edit this file, rerun gen.php to update!
class DatatableSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\Models\Datatable");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Datatable
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Datatable
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldname, $value): ?Datatable
    {
        return parent::getObjectByField($fieldname, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Datatable
    {
        return parent::current();
    }
    /**
     * uniqueIds
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIds(): array
    {
        return parent::uniqueArray("id");
    }
    /**
     * uniqueHideColZeros
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueHideColZeros(): array
    {
        return parent::uniqueArray("hideColZero");
    }
    /**
     * uniqueCols
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueCols(): array
    {
        return parent::uniqueArray("col");
    }
    /**
     * uniqueColss
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueColss(): array
    {
        return parent::uniqueArray("cols");
    }
    /**
     * uniqueNames
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueNames(): array
    {
        return parent::uniqueArray("name");
    }
    /**
     * uniqueDirs
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueDirs(): array
    {
        return parent::uniqueArray("dir");
    }
    // Loaders
    /**
     * loadById
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadById(
        int $id, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "id", 
            $id, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromIds
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromIds(array $values): array
    {
        return $this->loadIndexs("id", $values);
    }
    /**
     * loadByHideColZero
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByHideColZero(
        bool $hideColZero, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "hideColZero", 
            $hideColZero, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromHideColZeros
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromHideColZeros(array $values): array
    {
        return $this->loadIndexs("hideColZero", $values);
    }
    /**
     * loadByCol
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByCol(
        int $col, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "col", 
            $col, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromCols
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromCols(array $values): array
    {
        return $this->loadIndexs("col", $values);
    }
    /**
     * loadByCols
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByCols(
        string $cols, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "cols", 
            $cols, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromColss
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromColss(array $values): array
    {
        return $this->loadIndexs("cols", $values);
    }
    /**
     * loadByName
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByName(
        string $name, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "name", 
            $name, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromNames
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromNames(array $values): array
    {
        return $this->loadIndexs("name", $values);
    }
    /**
     * loadByDir
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByDir(
        string $dir, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "dir", 
            $dir, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromDirs
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromDirs(array $values): array
    {
        return $this->loadIndexs("dir", $values);
    }
    // Related loaders
}
