<?php

namespace App\Models\Sets;

use YAPF\Framework\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use App\Models\Eventsq as Eventsq;

// Do not edit this file, rerun gen.php to update!
class EventsqSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\Models\Eventsq");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Eventsq
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Eventsq
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldname, $value): ?Eventsq
    {
        return parent::getObjectByField($fieldname, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Eventsq
    {
        return parent::current();
    }
    /**
     * uniqueIds
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIds(): array
    {
        return parent::uniqueArray("id");
    }
    /**
     * uniqueEventNames
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueEventNames(): array
    {
        return parent::uniqueArray("eventName");
    }
    /**
     * uniqueEventMessages
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueEventMessages(): array
    {
        return parent::uniqueArray("eventMessage");
    }
    /**
     * uniqueEventUnixtimes
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueEventUnixtimes(): array
    {
        return parent::uniqueArray("eventUnixtime");
    }
    // Loaders
    /**
     * loadById
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadById(
        int $id, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "id", 
            $id, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromIds
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromIds(array $values): array
    {
        return $this->loadIndexs("id", $values);
    }
    /**
     * loadByEventName
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByEventName(
        string $eventName, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "eventName", 
            $eventName, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromEventNames
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromEventNames(array $values): array
    {
        return $this->loadIndexs("eventName", $values);
    }
    /**
     * loadByEventMessage
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByEventMessage(
        string $eventMessage, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "eventMessage", 
            $eventMessage, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromEventMessages
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromEventMessages(array $values): array
    {
        return $this->loadIndexs("eventMessage", $values);
    }
    /**
     * loadByEventUnixtime
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByEventUnixtime(
        int $eventUnixtime, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "eventUnixtime", 
            $eventUnixtime, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromEventUnixtimes
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromEventUnixtimes(array $values): array
    {
        return $this->loadIndexs("eventUnixtime", $values);
    }
    // Related loaders
}
