<?php

namespace App\Models\Sets;

use YAPF\Framework\Responses\DbObjects\SetsLoadReply as SetsLoadReply;
use YAPF\Framework\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use YAPF\Framework\Responses\DbObjects\UpdateReply as UpdateReply;
use App\Models\Eventsq as Eventsq;

// Do not edit this file, rerun gen.php to update!
class EventsqSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\Models\Eventsq");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Eventsq
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Eventsq
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldName, $value): ?Eventsq
    {
        return parent::getObjectByField($fieldName, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Eventsq
    {
        return parent::current();
    }
    /**
     * uniqueIds
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIds(): array
    {
        return parent::uniqueArray("id");
    }
    /**
     * uniqueEventNames
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueEventNames(): array
    {
        return parent::uniqueArray("eventName");
    }
    /**
     * uniqueEventMessages
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueEventMessages(): array
    {
        return parent::uniqueArray("eventMessage");
    }
    /**
     * uniqueEventUnixtimes
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueEventUnixtimes(): array
    {
        return parent::uniqueArray("eventUnixtime");
    }
    // Loaders
    /**
     * loadById
    */
    public function loadById(
        int $id,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "id",
            $id,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromIds
    */
    public function loadFromIds(array $values): SetsLoadReply
    {
        return $this->loadIndexes("id", $values);
    }
    /**
     * loadByEventName
    */
    public function loadByEventName(
        string $eventName,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "eventName",
            $eventName,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromEventNames
    */
    public function loadFromEventNames(array $values): SetsLoadReply
    {
        return $this->loadIndexes("eventName", $values);
    }
    /**
     * loadByEventMessage
    */
    public function loadByEventMessage(
        string $eventMessage,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "eventMessage",
            $eventMessage,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromEventMessages
    */
    public function loadFromEventMessages(array $values): SetsLoadReply
    {
        return $this->loadIndexes("eventMessage", $values);
    }
    /**
     * loadByEventUnixtime
    */
    public function loadByEventUnixtime(
        int $eventUnixtime,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "eventUnixtime",
            $eventUnixtime,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromEventUnixtimes
    */
    public function loadFromEventUnixtimes(array $values): SetsLoadReply
    {
        return $this->loadIndexes("eventUnixtime", $values);
    }
    // Related loaders
}
