<?php

namespace App\Models\Sets;

use YAPF\Framework\Responses\DbObjects\SetsLoadReply as SetsLoadReply;
use YAPF\Framework\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use YAPF\Framework\Responses\DbObjects\UpdateReply as UpdateReply;
use App\Models\Notecard as Notecard;

// Do not edit this file, rerun gen.php to update!
class NotecardSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\Models\Notecard");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Notecard
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Notecard
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldName, $value): ?Notecard
    {
        return parent::getObjectByField($fieldName, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Notecard
    {
        return parent::current();
    }
    /**
     * uniqueIds
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIds(): array
    {
        return parent::uniqueArray("id");
    }
    /**
     * uniqueRentalLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueRentalLinks(): array
    {
        return parent::uniqueArray("rentalLink");
    }
    /**
     * uniqueAsNotices
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueAsNotices(): array
    {
        return parent::uniqueArray("asNotice");
    }
    /**
     * uniqueNoticeLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueNoticeLinks(): array
    {
        return parent::uniqueArray("noticeLink");
    }
    // Loaders
    /**
     * loadById
    */
    public function loadById(
        int $id, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): SetsLoadReply
    {
        return $this->loadOnField(
            "id", 
            $id, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromIds
    */
    public function loadFromIds(array $values): SetsLoadReply
    {
        return $this->loadIndexes("id", $values);
    }
    /**
     * loadByRentalLink
    */
    public function loadByRentalLink(
        int $rentalLink, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): SetsLoadReply
    {
        return $this->loadOnField(
            "rentalLink", 
            $rentalLink, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromRentalLinks
    */
    public function loadFromRentalLinks(array $values): SetsLoadReply
    {
        return $this->loadIndexes("rentalLink", $values);
    }
    /**
     * loadByAsNotice
    */
    public function loadByAsNotice(
        bool $asNotice, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): SetsLoadReply
    {
        return $this->loadOnField(
            "asNotice", 
            $asNotice, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromAsNotices
    */
    public function loadFromAsNotices(array $values): SetsLoadReply
    {
        return $this->loadIndexes("asNotice", $values);
    }
    /**
     * loadByNoticeLink
    */
    public function loadByNoticeLink(
        int $noticeLink, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): SetsLoadReply
    {
        return $this->loadOnField(
            "noticeLink", 
            $noticeLink, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromNoticeLinks
    */
    public function loadFromNoticeLinks(array $values): SetsLoadReply
    {
        return $this->loadIndexes("noticeLink", $values);
    }
    // Related loaders
    public function relatedNotice(): NoticeSet
    {
        $ids = $this->uniqueNoticeLinks();
        $collection = new NoticeSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
    public function relatedRental(): RentalSet
    {
        $ids = $this->uniqueRentalLinks();
        $collection = new RentalSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
}
