<?php

namespace App\Models\Sets;

use YAPF\Framework\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use App\Models\Noticenotecard as Noticenotecard;

// Do not edit this file, rerun gen.php to update!
class NoticenotecardSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\Models\Noticenotecard");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Noticenotecard
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Noticenotecard
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldname, $value): ?Noticenotecard
    {
        return parent::getObjectByField($fieldname, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Noticenotecard
    {
        return parent::current();
    }
    /**
     * uniqueIds
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIds(): array
    {
        return parent::uniqueArray("id");
    }
    /**
     * uniqueNames
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueNames(): array
    {
        return parent::uniqueArray("name");
    }
    /**
     * uniqueMissings
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueMissings(): array
    {
        return parent::uniqueArray("missing");
    }
    // Loaders
    /**
     * loadById
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadById(
        int $id, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "id", 
            $id, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromIds
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromIds(array $values): array
    {
        return $this->loadIndexs("id", $values);
    }
    /**
     * loadByName
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByName(
        string $name, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "name", 
            $name, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromNames
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromNames(array $values): array
    {
        return $this->loadIndexs("name", $values);
    }
    /**
     * loadByMissing
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByMissing(
        bool $missing, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "missing", 
            $missing, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromMissings
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromMissings(array $values): array
    {
        return $this->loadIndexs("missing", $values);
    }
    // Related loaders
    public function relatedNotice(): NoticeSet
    {
        $ids = $this->uniqueIds();
        $collection = new NoticeSet();
        $collection->loadFromNoticeNotecardLinks($ids);
        return $collection;
    }
    public function relatedPackage(): PackageSet
    {
        $ids = $this->uniqueIds();
        $collection = new PackageSet();
        $collection->loadFromWelcomeNotecardLinks($ids);
        return $collection;
    }
}
