<?php

namespace App\Models\Sets;

use YAPF\Framework\Responses\DbObjects\SetsLoadReply as SetsLoadReply;
use YAPF\Framework\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use YAPF\Framework\Responses\DbObjects\UpdateReply as UpdateReply;
use App\Models\Slconfig as Slconfig;

// Do not edit this file, rerun gen.php to update!
class SlconfigSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\Models\Slconfig");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Slconfig
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Slconfig
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldName, $value): ?Slconfig
    {
        return parent::getObjectByField($fieldName, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Slconfig
    {
        return parent::current();
    }
    /**
     * uniqueIds
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIds(): array
    {
        return parent::uniqueArray("id");
    }
    /**
     * uniqueDbVersions
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueDbVersions(): array
    {
        return parent::uniqueArray("dbVersion");
    }
    /**
     * uniqueNewResellerss
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueNewResellerss(): array
    {
        return parent::uniqueArray("newResellers");
    }
    /**
     * uniqueNewResellersRates
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueNewResellersRates(): array
    {
        return parent::uniqueArray("newResellersRate");
    }
    /**
     * uniqueSlLinkCodes
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueSlLinkCodes(): array
    {
        return parent::uniqueArray("slLinkCode");
    }
    /**
     * uniqueClientsListModes
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueClientsListModes(): array
    {
        return parent::uniqueArray("clientsListMode");
    }
    /**
     * uniquePublicLinkCodes
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniquePublicLinkCodes(): array
    {
        return parent::uniqueArray("publicLinkCode");
    }
    /**
     * uniqueHudLinkCodes
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueHudLinkCodes(): array
    {
        return parent::uniqueArray("hudLinkCode");
    }
    /**
     * uniqueOwnerAvatarLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueOwnerAvatarLinks(): array
    {
        return parent::uniqueArray("ownerAvatarLink");
    }
    /**
     * uniqueDatatableItemsPerPages
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueDatatableItemsPerPages(): array
    {
        return parent::uniqueArray("datatableItemsPerPage");
    }
    /**
     * uniqueHttpInboundSecrets
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueHttpInboundSecrets(): array
    {
        return parent::uniqueArray("httpInboundSecret");
    }
    /**
     * uniqueDisplayTimezoneLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueDisplayTimezoneLinks(): array
    {
        return parent::uniqueArray("displayTimezoneLink");
    }
    /**
     * uniqueHudAllowDiscords
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueHudAllowDiscords(): array
    {
        return parent::uniqueArray("hudAllowDiscord");
    }
    /**
     * uniqueHudDiscordLinks
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueHudDiscordLinks(): array
    {
        return parent::uniqueArray("hudDiscordLink");
    }
    /**
     * uniqueHudAllowGroups
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueHudAllowGroups(): array
    {
        return parent::uniqueArray("hudAllowGroup");
    }
    /**
     * uniqueHudGroupLinks
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueHudGroupLinks(): array
    {
        return parent::uniqueArray("hudGroupLink");
    }
    /**
     * uniqueHudAllowDetailss
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueHudAllowDetailss(): array
    {
        return parent::uniqueArray("hudAllowDetails");
    }
    /**
     * uniqueHudAllowRenewals
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueHudAllowRenewals(): array
    {
        return parent::uniqueArray("hudAllowRenewal");
    }
    /**
     * uniqueEventsAPIs
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueEventsAPIs(): array
    {
        return parent::uniqueArray("eventsAPI");
    }
    /**
     * uniquePaymentKeys
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniquePaymentKeys(): array
    {
        return parent::uniqueArray("paymentKey");
    }
    /**
     * uniqueStreamListOptions
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueStreamListOptions(): array
    {
        return parent::uniqueArray("streamListOption");
    }
    /**
     * uniqueClientsDisplayServers
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueClientsDisplayServers(): array
    {
        return parent::uniqueArray("clientsDisplayServer");
    }
    /**
     * uniqueLimitStreamss
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueLimitStreamss(): array
    {
        return parent::uniqueArray("limitStreams");
    }
    /**
     * uniqueLimitTimes
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueLimitTimes(): array
    {
        return parent::uniqueArray("limitTime");
    }
    /**
     * uniqueMaxStreamTimeDayss
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueMaxStreamTimeDayss(): array
    {
        return parent::uniqueArray("maxStreamTimeDays");
    }
    /**
     * uniqueMaxTotalStreamss
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueMaxTotalStreamss(): array
    {
        return parent::uniqueArray("maxTotalStreams");
    }
    // Loaders
    /**
     * loadById
    */
    public function loadById(
        int $id,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "id",
            $id,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromIds
    */
    public function loadFromIds(array $values): SetsLoadReply
    {
        return $this->loadIndexes("id", $values);
    }
    /**
     * loadByDbVersion
    */
    public function loadByDbVersion(
        string $dbVersion,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "dbVersion",
            $dbVersion,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromDbVersions
    */
    public function loadFromDbVersions(array $values): SetsLoadReply
    {
        return $this->loadIndexes("dbVersion", $values);
    }
    /**
     * loadByNewResellers
    */
    public function loadByNewResellers(
        bool $newResellers,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "newResellers",
            $newResellers,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromNewResellerss
    */
    public function loadFromNewResellerss(array $values): SetsLoadReply
    {
        return $this->loadIndexes("newResellers", $values);
    }
    /**
     * loadByNewResellersRate
    */
    public function loadByNewResellersRate(
        int $newResellersRate,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "newResellersRate",
            $newResellersRate,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromNewResellersRates
    */
    public function loadFromNewResellersRates(array $values): SetsLoadReply
    {
        return $this->loadIndexes("newResellersRate", $values);
    }
    /**
     * loadBySlLinkCode
    */
    public function loadBySlLinkCode(
        string $slLinkCode,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "slLinkCode",
            $slLinkCode,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromSlLinkCodes
    */
    public function loadFromSlLinkCodes(array $values): SetsLoadReply
    {
        return $this->loadIndexes("slLinkCode", $values);
    }
    /**
     * loadByClientsListMode
    */
    public function loadByClientsListMode(
        bool $clientsListMode,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "clientsListMode",
            $clientsListMode,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromClientsListModes
    */
    public function loadFromClientsListModes(array $values): SetsLoadReply
    {
        return $this->loadIndexes("clientsListMode", $values);
    }
    /**
     * loadByPublicLinkCode
    */
    public function loadByPublicLinkCode(
        string $publicLinkCode,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "publicLinkCode",
            $publicLinkCode,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromPublicLinkCodes
    */
    public function loadFromPublicLinkCodes(array $values): SetsLoadReply
    {
        return $this->loadIndexes("publicLinkCode", $values);
    }
    /**
     * loadByHudLinkCode
    */
    public function loadByHudLinkCode(
        string $hudLinkCode,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "hudLinkCode",
            $hudLinkCode,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromHudLinkCodes
    */
    public function loadFromHudLinkCodes(array $values): SetsLoadReply
    {
        return $this->loadIndexes("hudLinkCode", $values);
    }
    /**
     * loadByOwnerAvatarLink
    */
    public function loadByOwnerAvatarLink(
        int $ownerAvatarLink,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "ownerAvatarLink",
            $ownerAvatarLink,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromOwnerAvatarLinks
    */
    public function loadFromOwnerAvatarLinks(array $values): SetsLoadReply
    {
        return $this->loadIndexes("ownerAvatarLink", $values);
    }
    /**
     * loadByDatatableItemsPerPage
    */
    public function loadByDatatableItemsPerPage(
        int $datatableItemsPerPage,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "datatableItemsPerPage",
            $datatableItemsPerPage,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromDatatableItemsPerPages
    */
    public function loadFromDatatableItemsPerPages(array $values): SetsLoadReply
    {
        return $this->loadIndexes("datatableItemsPerPage", $values);
    }
    /**
     * loadByHttpInboundSecret
    */
    public function loadByHttpInboundSecret(
        string $httpInboundSecret,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "httpInboundSecret",
            $httpInboundSecret,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromHttpInboundSecrets
    */
    public function loadFromHttpInboundSecrets(array $values): SetsLoadReply
    {
        return $this->loadIndexes("httpInboundSecret", $values);
    }
    /**
     * loadByDisplayTimezoneLink
    */
    public function loadByDisplayTimezoneLink(
        int $displayTimezoneLink,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "displayTimezoneLink",
            $displayTimezoneLink,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromDisplayTimezoneLinks
    */
    public function loadFromDisplayTimezoneLinks(array $values): SetsLoadReply
    {
        return $this->loadIndexes("displayTimezoneLink", $values);
    }
    /**
     * loadByHudAllowDiscord
    */
    public function loadByHudAllowDiscord(
        bool $hudAllowDiscord,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "hudAllowDiscord",
            $hudAllowDiscord,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromHudAllowDiscords
    */
    public function loadFromHudAllowDiscords(array $values): SetsLoadReply
    {
        return $this->loadIndexes("hudAllowDiscord", $values);
    }
    /**
     * loadByHudDiscordLink
    */
    public function loadByHudDiscordLink(
        string $hudDiscordLink,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "hudDiscordLink",
            $hudDiscordLink,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromHudDiscordLinks
    */
    public function loadFromHudDiscordLinks(array $values): SetsLoadReply
    {
        return $this->loadIndexes("hudDiscordLink", $values);
    }
    /**
     * loadByHudAllowGroup
    */
    public function loadByHudAllowGroup(
        bool $hudAllowGroup,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "hudAllowGroup",
            $hudAllowGroup,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromHudAllowGroups
    */
    public function loadFromHudAllowGroups(array $values): SetsLoadReply
    {
        return $this->loadIndexes("hudAllowGroup", $values);
    }
    /**
     * loadByHudGroupLink
    */
    public function loadByHudGroupLink(
        string $hudGroupLink,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "hudGroupLink",
            $hudGroupLink,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromHudGroupLinks
    */
    public function loadFromHudGroupLinks(array $values): SetsLoadReply
    {
        return $this->loadIndexes("hudGroupLink", $values);
    }
    /**
     * loadByHudAllowDetails
    */
    public function loadByHudAllowDetails(
        bool $hudAllowDetails,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "hudAllowDetails",
            $hudAllowDetails,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromHudAllowDetailss
    */
    public function loadFromHudAllowDetailss(array $values): SetsLoadReply
    {
        return $this->loadIndexes("hudAllowDetails", $values);
    }
    /**
     * loadByHudAllowRenewal
    */
    public function loadByHudAllowRenewal(
        bool $hudAllowRenewal,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "hudAllowRenewal",
            $hudAllowRenewal,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromHudAllowRenewals
    */
    public function loadFromHudAllowRenewals(array $values): SetsLoadReply
    {
        return $this->loadIndexes("hudAllowRenewal", $values);
    }
    /**
     * loadByEventsAPI
    */
    public function loadByEventsAPI(
        bool $eventsAPI,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "eventsAPI",
            $eventsAPI,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromEventsAPIs
    */
    public function loadFromEventsAPIs(array $values): SetsLoadReply
    {
        return $this->loadIndexes("eventsAPI", $values);
    }
    /**
     * loadByPaymentKey
    */
    public function loadByPaymentKey(
        string $paymentKey,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "paymentKey",
            $paymentKey,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromPaymentKeys
    */
    public function loadFromPaymentKeys(array $values): SetsLoadReply
    {
        return $this->loadIndexes("paymentKey", $values);
    }
    /**
     * loadByStreamListOption
    */
    public function loadByStreamListOption(
        int $streamListOption,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "streamListOption",
            $streamListOption,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromStreamListOptions
    */
    public function loadFromStreamListOptions(array $values): SetsLoadReply
    {
        return $this->loadIndexes("streamListOption", $values);
    }
    /**
     * loadByClientsDisplayServer
    */
    public function loadByClientsDisplayServer(
        bool $clientsDisplayServer,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "clientsDisplayServer",
            $clientsDisplayServer,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromClientsDisplayServers
    */
    public function loadFromClientsDisplayServers(array $values): SetsLoadReply
    {
        return $this->loadIndexes("clientsDisplayServer", $values);
    }
    /**
     * loadByLimitStreams
    */
    public function loadByLimitStreams(
        bool $limitStreams,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "limitStreams",
            $limitStreams,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromLimitStreamss
    */
    public function loadFromLimitStreamss(array $values): SetsLoadReply
    {
        return $this->loadIndexes("limitStreams", $values);
    }
    /**
     * loadByLimitTime
    */
    public function loadByLimitTime(
        bool $limitTime,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "limitTime",
            $limitTime,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromLimitTimes
    */
    public function loadFromLimitTimes(array $values): SetsLoadReply
    {
        return $this->loadIndexes("limitTime", $values);
    }
    /**
     * loadByMaxStreamTimeDays
    */
    public function loadByMaxStreamTimeDays(
        int $maxStreamTimeDays,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "maxStreamTimeDays",
            $maxStreamTimeDays,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromMaxStreamTimeDayss
    */
    public function loadFromMaxStreamTimeDayss(array $values): SetsLoadReply
    {
        return $this->loadIndexes("maxStreamTimeDays", $values);
    }
    /**
     * loadByMaxTotalStreams
    */
    public function loadByMaxTotalStreams(
        int $maxTotalStreams,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): SetsLoadReply {
        return $this->loadOnField(
            "maxTotalStreams",
            $maxTotalStreams,
            $limit,
            $orderBy,
            $orderDir
        );
    }
    /**
     * loadFromMaxTotalStreamss
    */
    public function loadFromMaxTotalStreamss(array $values): SetsLoadReply
    {
        return $this->loadIndexes("maxTotalStreams", $values);
    }
    // Related loaders
    public function relatedAvatar(?array $limitFields=null): AvatarSet
    {
        $ids = $this->uniqueOwnerAvatarLinks();
        $collection = new AvatarSet();
        if($limitFields !== null) {
            $collection->limitFields($limitFields);
        }
        $collection->loadFromIds($ids);
        return $collection;
    }
    public function relatedTimezones(?array $limitFields=null): TimezonesSet
    {
        $ids = $this->uniqueDisplayTimezoneLinks();
        $collection = new TimezonesSet();
        if($limitFields !== null) {
            $collection->limitFields($limitFields);
        }
        $collection->loadFromIds($ids);
        return $collection;
    }
}
