<?php

namespace App\Models\Sets;

use YAPF\Framework\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use App\Models\Staff as Staff;

// Do not edit this file, rerun gen.php to update!
class StaffSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\Models\Staff");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Staff
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Staff
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldname, $value): ?Staff
    {
        return parent::getObjectByField($fieldname, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Staff
    {
        return parent::current();
    }
    /**
     * uniqueIds
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIds(): array
    {
        return parent::uniqueArray("id");
    }
    /**
     * uniqueUsernames
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueUsernames(): array
    {
        return parent::uniqueArray("username");
    }
    /**
     * uniqueEmailResetCodes
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueEmailResetCodes(): array
    {
        return parent::uniqueArray("emailResetCode");
    }
    /**
     * uniqueEmailResetExpiress
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueEmailResetExpiress(): array
    {
        return parent::uniqueArray("emailResetExpires");
    }
    /**
     * uniqueAvatarLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueAvatarLinks(): array
    {
        return parent::uniqueArray("avatarLink");
    }
    /**
     * uniquePhashs
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniquePhashs(): array
    {
        return parent::uniqueArray("phash");
    }
    /**
     * uniqueLhashs
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueLhashs(): array
    {
        return parent::uniqueArray("lhash");
    }
    /**
     * uniquePsalts
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniquePsalts(): array
    {
        return parent::uniqueArray("psalt");
    }
    /**
     * uniqueOwnerLevels
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueOwnerLevels(): array
    {
        return parent::uniqueArray("ownerLevel");
    }
    // Loaders
    /**
     * loadById
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadById(
        int $id, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "id", 
            $id, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromIds
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromIds(array $values): array
    {
        return $this->loadIndexs("id", $values);
    }
    /**
     * loadByUsername
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByUsername(
        string $username, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "username", 
            $username, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromUsernames
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromUsernames(array $values): array
    {
        return $this->loadIndexs("username", $values);
    }
    /**
     * loadByEmailResetCode
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByEmailResetCode(
        string $emailResetCode, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "emailResetCode", 
            $emailResetCode, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromEmailResetCodes
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromEmailResetCodes(array $values): array
    {
        return $this->loadIndexs("emailResetCode", $values);
    }
    /**
     * loadByEmailResetExpires
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByEmailResetExpires(
        int $emailResetExpires, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "emailResetExpires", 
            $emailResetExpires, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromEmailResetExpiress
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromEmailResetExpiress(array $values): array
    {
        return $this->loadIndexs("emailResetExpires", $values);
    }
    /**
     * loadByAvatarLink
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByAvatarLink(
        int $avatarLink, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "avatarLink", 
            $avatarLink, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromAvatarLinks
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromAvatarLinks(array $values): array
    {
        return $this->loadIndexs("avatarLink", $values);
    }
    /**
     * loadByPhash
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByPhash(
        string $phash, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "phash", 
            $phash, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromPhashs
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromPhashs(array $values): array
    {
        return $this->loadIndexs("phash", $values);
    }
    /**
     * loadByLhash
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByLhash(
        string $lhash, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "lhash", 
            $lhash, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromLhashs
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromLhashs(array $values): array
    {
        return $this->loadIndexs("lhash", $values);
    }
    /**
     * loadByPsalt
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByPsalt(
        string $psalt, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "psalt", 
            $psalt, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromPsalts
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromPsalts(array $values): array
    {
        return $this->loadIndexs("psalt", $values);
    }
    /**
     * loadByOwnerLevel
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByOwnerLevel(
        bool $ownerLevel, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "ownerLevel", 
            $ownerLevel, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromOwnerLevels
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromOwnerLevels(array $values): array
    {
        return $this->loadIndexs("ownerLevel", $values);
    }
    // Related loaders
    public function relatedAvatar(): AvatarSet
    {
        $ids = $this->uniqueAvatarLinks();
        $collection = new AvatarSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
}
