<?php

namespace App\Models\Sets;

use YAPF\Framework\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use App\Models\Transactions as Transactions;

// Do not edit this file, rerun gen.php to update!
class TransactionsSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\Models\Transactions");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Transactions
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Transactions
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldname, $value): ?Transactions
    {
        return parent::getObjectByField($fieldname, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Transactions
    {
        return parent::current();
    }
    /**
     * uniqueIds
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIds(): array
    {
        return parent::uniqueArray("id");
    }
    /**
     * uniqueAvatarLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueAvatarLinks(): array
    {
        return parent::uniqueArray("avatarLink");
    }
    /**
     * uniquePackageLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniquePackageLinks(): array
    {
        return parent::uniqueArray("packageLink");
    }
    /**
     * uniqueStreamLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueStreamLinks(): array
    {
        return parent::uniqueArray("streamLink");
    }
    /**
     * uniqueResellerLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueResellerLinks(): array
    {
        return parent::uniqueArray("resellerLink");
    }
    /**
     * uniqueRegionLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueRegionLinks(): array
    {
        return parent::uniqueArray("regionLink");
    }
    /**
     * uniqueAmounts
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueAmounts(): array
    {
        return parent::uniqueArray("amount");
    }
    /**
     * uniqueUnixtimes
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueUnixtimes(): array
    {
        return parent::uniqueArray("unixtime");
    }
    /**
     * uniqueTransactionUids
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueTransactionUids(): array
    {
        return parent::uniqueArray("transactionUid");
    }
    /**
     * uniqueRenews
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueRenews(): array
    {
        return parent::uniqueArray("renew");
    }
    /**
     * uniqueSLtransactionUUIDs
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueSLtransactionUUIDs(): array
    {
        return parent::uniqueArray("SLtransactionUUID");
    }
    /**
     * uniqueViaHuds
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueViaHuds(): array
    {
        return parent::uniqueArray("ViaHud");
    }
    // Loaders
    /**
     * loadById
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadById(
        int $id, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "id", 
            $id, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromIds
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromIds(array $values): array
    {
        return $this->loadIndexs("id", $values);
    }
    /**
     * loadByAvatarLink
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByAvatarLink(
        int $avatarLink, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "avatarLink", 
            $avatarLink, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromAvatarLinks
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromAvatarLinks(array $values): array
    {
        return $this->loadIndexs("avatarLink", $values);
    }
    /**
     * loadByPackageLink
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByPackageLink(
        int $packageLink, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "packageLink", 
            $packageLink, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromPackageLinks
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromPackageLinks(array $values): array
    {
        return $this->loadIndexs("packageLink", $values);
    }
    /**
     * loadByStreamLink
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByStreamLink(
        int $streamLink, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "streamLink", 
            $streamLink, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromStreamLinks
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromStreamLinks(array $values): array
    {
        return $this->loadIndexs("streamLink", $values);
    }
    /**
     * loadByResellerLink
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByResellerLink(
        int $resellerLink, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "resellerLink", 
            $resellerLink, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromResellerLinks
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromResellerLinks(array $values): array
    {
        return $this->loadIndexs("resellerLink", $values);
    }
    /**
     * loadByRegionLink
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByRegionLink(
        int $regionLink, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "regionLink", 
            $regionLink, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromRegionLinks
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromRegionLinks(array $values): array
    {
        return $this->loadIndexs("regionLink", $values);
    }
    /**
     * loadByAmount
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByAmount(
        int $amount, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "amount", 
            $amount, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromAmounts
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromAmounts(array $values): array
    {
        return $this->loadIndexs("amount", $values);
    }
    /**
     * loadByUnixtime
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByUnixtime(
        int $unixtime, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "unixtime", 
            $unixtime, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromUnixtimes
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromUnixtimes(array $values): array
    {
        return $this->loadIndexs("unixtime", $values);
    }
    /**
     * loadByTransactionUid
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByTransactionUid(
        string $transactionUid, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "transactionUid", 
            $transactionUid, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromTransactionUids
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromTransactionUids(array $values): array
    {
        return $this->loadIndexs("transactionUid", $values);
    }
    /**
     * loadByRenew
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByRenew(
        bool $renew, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "renew", 
            $renew, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromRenews
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromRenews(array $values): array
    {
        return $this->loadIndexs("renew", $values);
    }
    /**
     * loadBySLtransactionUUID
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadBySLtransactionUUID(
        string $SLtransactionUUID, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "SLtransactionUUID", 
            $SLtransactionUUID, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromSLtransactionUUIDs
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromSLtransactionUUIDs(array $values): array
    {
        return $this->loadIndexs("SLtransactionUUID", $values);
    }
    /**
     * loadByViaHud
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByViaHud(
        bool $ViaHud, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "ViaHud", 
            $ViaHud, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromViaHuds
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromViaHuds(array $values): array
    {
        return $this->loadIndexs("ViaHud", $values);
    }
    // Related loaders
    public function relatedAvatar(): AvatarSet
    {
        $ids = $this->uniqueAvatarLinks();
        $collection = new AvatarSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
    public function relatedPackage(): PackageSet
    {
        $ids = $this->uniquePackageLinks();
        $collection = new PackageSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
    public function relatedRegion(): RegionSet
    {
        $ids = $this->uniqueRegionLinks();
        $collection = new RegionSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
    public function relatedReseller(): ResellerSet
    {
        $ids = $this->uniqueResellerLinks();
        $collection = new ResellerSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
    public function relatedStream(): StreamSet
    {
        $ids = $this->uniqueStreamLinks();
        $collection = new StreamSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
}
