<?php

namespace App\Models\Sets;

use YAPF\Framework\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use App\Models\Treevenderpackages as Treevenderpackages;

// Do not edit this file, rerun gen.php to update!
class TreevenderpackagesSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\Models\Treevenderpackages");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Treevenderpackages
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Treevenderpackages
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldname, $value): ?Treevenderpackages
    {
        return parent::getObjectByField($fieldname, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Treevenderpackages
    {
        return parent::current();
    }
    /**
     * uniqueIds
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIds(): array
    {
        return parent::uniqueArray("id");
    }
    /**
     * uniqueTreevenderLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueTreevenderLinks(): array
    {
        return parent::uniqueArray("treevenderLink");
    }
    /**
     * uniquePackageLinks
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniquePackageLinks(): array
    {
        return parent::uniqueArray("packageLink");
    }
    // Loaders
    /**
     * loadById
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadById(
        int $id, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "id", 
            $id, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromIds
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromIds(array $values): array
    {
        return $this->loadIndexs("id", $values);
    }
    /**
     * loadByTreevenderLink
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByTreevenderLink(
        int $treevenderLink, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "treevenderLink", 
            $treevenderLink, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromTreevenderLinks
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromTreevenderLinks(array $values): array
    {
        return $this->loadIndexs("treevenderLink", $values);
    }
    /**
     * loadByPackageLink
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByPackageLink(
        int $packageLink, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "packageLink", 
            $packageLink, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromPackageLinks
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromPackageLinks(array $values): array
    {
        return $this->loadIndexs("packageLink", $values);
    }
    // Related loaders
    public function relatedPackage(): PackageSet
    {
        $ids = $this->uniquePackageLinks();
        $collection = new PackageSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
    public function relatedTreevender(): TreevenderSet
    {
        $ids = $this->uniqueTreevenderLinks();
        $collection = new TreevenderSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
}
