version: '3'
services:
    app:
        container_name: SA7Website
        restart: always
        image: madpeter/streamadmin_r7:azurecastdev
        networks:
        - streamadmin_network
        - bridge
        ports:
        - 8082:80
        expose:
        - '8882/tcp'
        depends_on:
        - db
        - redis
        environment:
        - SITE_HOST="https://streamadmin.magicmadpeter.xyz/"
        - SITE_TITLE="StreamAdmin"
        - SITE_LANG="en"
        - DB_HOST=db
        - DB_DATABASE="streamadmin"
        - DB_USERNAME="streamadminDBuser"
        - DB_PASSWORD="zZ2apJxqo3uJHc"
        - REDIS_HOST=redis
        - SESSION_DRIVER=redis
        - CACHE_DRIVER=redis
        - INSTALL_OK=0

    db:
        container_name: SA7Db
        image: mariadb
        restart: always
        networks:
        - streamadmin_network
        environment:
        - MYSQL_RANDOM_ROOT_PASSWORD="yes"
        - MYSQL_ALLOW_EMPTY_PASSWORD="no"
        - MYSQL_USER="streamadminDBuser"
        - MYSQL_PASSWORD="zZ2apJxqo3uJHc"
        - MYSQL_DATABASE=streamadmin
        volumes:
        - streamadmin-db:/var/lib/mysql

    phpmyadmin:
        container_name: SA7PHPmyAdmin
        environment:
        - PMA_HOST=db
        networks:
        - streamadmin_network
        - bridge
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
        - 8081:80
        expose:
        - '8881/tcp'
        depends_on:
        - db

    redis:
        container_name: SA7Redis
        image: redis:4.0-alpine
        networks:
        - streamadmin_network

networks:
  streamadmin_network:
  bridge:

volumes:
  streamadmin-db: