# Replace {DOMAIN} with your domain example: https://streamadmin.magicmadpeter.xyz/
# Replace {DBPASSWORD} with a random password used to sign into phpmyadmin

version: '3'
services:
    app:
        container_name: SA7Website
        restart: always
        image: madpeter/streamadmin_r7:dev
        networks:
        - streamadmin
        ports:
        - 8082:80
        expose:
        - '8082/tcp'
        depends_on:
        - SA7Db
        - SA7Dbredis
        environment:
        - SITE_NAME={DOMAIN}
        - SITE_URL=StreamAdmin
        - SITE_CACHE_ENABLED=true
        - SITE_CACHE_REDIS_HOST=SA7Dbredis
        - SQL_HOST=SA7Db
        - SQL_DB_NAME=streamadmin
        - SQL_DB_USER=streamadminDBuser
        - SQL_DB_PASS={DBPASSWORD}
        - REDIS_HOST=SA7Dbredis
        - SESSION_DRIVER=redis
        - CACHE_DRIVER=redis
        volumes:
          - type: bind
            source: /srv/logs
            target: /srv/logs

    SA7Db:
        container_name: SA7Db
        image: mariadb
        restart: always
        networks:
        - streamadmin
        environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_ALLOW_EMPTY_PASSWORD=no
        - MYSQL_USER=streamadminDBuser
        - MYSQL_PASSWORD={DBPASSWORD}
        - MYSQL_DATABASE=streamadmin
        volumes:
        - streamadmin-db:/var/lib/mysql

    SA7Dbphpmyadmin:
        container_name: SA7PHPmyAdmin
        environment:
        - PMA_HOST=SA7Db
        networks:
        - streamadmin
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
        - 8881:80
        expose:
        - '8881/tcp'
        depends_on:
        - SA7Db

    SA7Dbredis:
        container_name: SA7Redis
        image: redis:4.0-alpine
        networks:
        - streamadmin

networks:
  streamadmin:

volumes:
  streamadmin-db:
