// Replace {DOMAIN} with the http or http url to the site with a ending /
// Replace {PASS} with the SQL db password
// Replace {TAG} with the target version example 2.0.1.0
services:
    SA7Website:
        container_name: SA7Website
        restart: always
        image: madpeter/streamadmin:{TAG}
        networks:
        - streamadmin
        ports:
        - 8082:80
        expose:
        - '8082/tcp'
        depends_on:
        - SA7Db
        - SA7Redis
        environment:
        - SITE_NAME=Streamadmin
        - SITE_URL={DOMAIN}
        - SITE_CACHE_ENABLED=true
        - SITE_CACHE_REDIS_HOST=SA7Redis
        - SQL_HOST=SA7Db
        - SQL_DB_NAME=streamadmin
        - SQL_DB_USER=streamadminDBuser
        - SQL_DB_PASS={PASS}
        - REDIS_HOST=SA7Redis
        - SESSION_DRIVER=redis
        - CACHE_DRIVER=redis

    SA7Cron:
        container_name: SA7Cron
        restart: always
        image: madpeter/streamadmin:{TAG}
        entrypoint: /bin/bash
        command: [".docker/CronEntrypoint.sh"]
        networks:
        - streamadmin
        depends_on:
        - SA7Db
        - SA7Redis
        - SA7Website
        environment:
        - SITE_NAME=Streamadmin
        - SITE_URL={DOMAIN}
        - SITE_CACHE_ENABLED=true
        - SITE_CACHE_REDIS_HOST=SA7Redis
        - SQL_HOST=SA7Db
        - SQL_DB_NAME=streamadmin
        - SQL_DB_USER=streamadminDBuser
        - SQL_DB_PASS={PASS}
        - REDIS_HOST=SA7Redis
        - SESSION_DRIVER=redis
        - CACHE_DRIVER=redis

    SA7Db:
        container_name: SA7Db
        image: mariadb
        restart: always
        networks:
        - streamadmin
        environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_ALLOW_EMPTY_PASSWORD=no
        - MYSQL_USER=streamadminDBuser
        - MYSQL_PASSWORD={PASS}
        - MYSQL_DATABASE=streamadmin
        volumes:
        - streamadmin-db:/var/lib/mysql

    SA7PHPmyAdmin:
        container_name: SA7PHPmyAdmin
        environment:
        - PMA_HOST=SA7Db
        - UPLOAD_LIMIT=300M
        networks:
        - streamadmin
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
        - 8881:80
        expose:
        - '8881/tcp'
        depends_on:
        - SA7Db

    SA7Redis:
        container_name: SA7Redis
        image: redis:4.0-alpine
        networks:
        - streamadmin

networks:
  streamadmin:

volumes:
  streamadmin-db:
