<?php

namespace App\R4\Model;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Items extends genClass
{
    protected $use_table = "items";
    // Data Design
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "packageid" => ["type" => "int", "value" => null],
        "sold" => ["type" => "int", "value" => 0],
        "streamurl" => ["type" => "str", "value" => null],
        "streamport" => ["type" => "str", "value" => null],
        "streampassword" => ["type" => "str", "value" => null],
        "baditem" => ["type" => "int", "value" => 0],
        "adminurl" => ["type" => "str", "value" => null],
        "adminusername" => ["type" => "str", "value" => null],
        "adminpassword" => ["type" => "str", "value" => null],
        "serverlocid" => ["type" => "int", "value" => 1],
        "addon1" => ["type" => "str", "value" => null],
        "addon2" => ["type" => "str", "value" => null],
        "addon3" => ["type" => "str", "value" => null],
        "addon4" => ["type" => "str", "value" => null],
    ];
    // Getters
    public function getPackageid(): ?int
    {
        return $this->getField("packageid");
    }
    public function getSold(): ?int
    {
        return $this->getField("sold");
    }
    public function getStreamurl(): ?string
    {
        return $this->getField("streamurl");
    }
    public function getStreamport(): ?string
    {
        return $this->getField("streamport");
    }
    public function getStreampassword(): ?string
    {
        return $this->getField("streampassword");
    }
    public function getBaditem(): ?int
    {
        return $this->getField("baditem");
    }
    public function getAdminurl(): ?string
    {
        return $this->getField("adminurl");
    }
    public function getAdminusername(): ?string
    {
        return $this->getField("adminusername");
    }
    public function getAdminpassword(): ?string
    {
        return $this->getField("adminpassword");
    }
    public function getServerlocid(): ?int
    {
        return $this->getField("serverlocid");
    }
    public function getAddon1(): ?string
    {
        return $this->getField("addon1");
    }
    public function getAddon2(): ?string
    {
        return $this->getField("addon2");
    }
    public function getAddon3(): ?string
    {
        return $this->getField("addon3");
    }
    public function getAddon4(): ?string
    {
        return $this->getField("addon4");
    }
    // Setters
    /**
    * setPackageid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setPackageid(?int $newvalue): array
    {
        return $this->updateField("packageid", $newvalue);
    }
    /**
    * setSold
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setSold(?int $newvalue): array
    {
        return $this->updateField("sold", $newvalue);
    }
    /**
    * setStreamurl
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setStreamurl(?string $newvalue): array
    {
        return $this->updateField("streamurl", $newvalue);
    }
    /**
    * setStreamport
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setStreamport(?string $newvalue): array
    {
        return $this->updateField("streamport", $newvalue);
    }
    /**
    * setStreampassword
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setStreampassword(?string $newvalue): array
    {
        return $this->updateField("streampassword", $newvalue);
    }
    /**
    * setBaditem
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBaditem(?int $newvalue): array
    {
        return $this->updateField("baditem", $newvalue);
    }
    /**
    * setAdminurl
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAdminurl(?string $newvalue): array
    {
        return $this->updateField("adminurl", $newvalue);
    }
    /**
    * setAdminusername
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAdminusername(?string $newvalue): array
    {
        return $this->updateField("adminusername", $newvalue);
    }
    /**
    * setAdminpassword
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAdminpassword(?string $newvalue): array
    {
        return $this->updateField("adminpassword", $newvalue);
    }
    /**
    * setServerlocid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setServerlocid(?int $newvalue): array
    {
        return $this->updateField("serverlocid", $newvalue);
    }
    /**
    * setAddon1
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAddon1(?string $newvalue): array
    {
        return $this->updateField("addon1", $newvalue);
    }
    /**
    * setAddon2
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAddon2(?string $newvalue): array
    {
        return $this->updateField("addon2", $newvalue);
    }
    /**
    * setAddon3
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAddon3(?string $newvalue): array
    {
        return $this->updateField("addon3", $newvalue);
    }
    /**
    * setAddon4
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAddon4(?string $newvalue): array
    {
        return $this->updateField("addon4", $newvalue);
    }
    // Loaders
    public function loadByPackageid(int $packageid): bool
    {
        return $this->loadByField("packageid", $packageid);
    }
    public function loadBySold(int $sold): bool
    {
        return $this->loadByField("sold", $sold);
    }
    public function loadByStreamurl(string $streamurl): bool
    {
        return $this->loadByField("streamurl", $streamurl);
    }
    public function loadByStreamport(string $streamport): bool
    {
        return $this->loadByField("streamport", $streamport);
    }
    public function loadByStreampassword(string $streampassword): bool
    {
        return $this->loadByField("streampassword", $streampassword);
    }
    public function loadByBaditem(int $baditem): bool
    {
        return $this->loadByField("baditem", $baditem);
    }
    public function loadByAdminurl(string $adminurl): bool
    {
        return $this->loadByField("adminurl", $adminurl);
    }
    public function loadByAdminusername(string $adminusername): bool
    {
        return $this->loadByField("adminusername", $adminusername);
    }
    public function loadByAdminpassword(string $adminpassword): bool
    {
        return $this->loadByField("adminpassword", $adminpassword);
    }
    public function loadByServerlocid(int $serverlocid): bool
    {
        return $this->loadByField("serverlocid", $serverlocid);
    }
    public function loadByAddon1(string $addon1): bool
    {
        return $this->loadByField("addon1", $addon1);
    }
    public function loadByAddon2(string $addon2): bool
    {
        return $this->loadByField("addon2", $addon2);
    }
    public function loadByAddon3(string $addon3): bool
    {
        return $this->loadByField("addon3", $addon3);
    }
    public function loadByAddon4(string $addon4): bool
    {
        return $this->loadByField("addon4", $addon4);
    }
}
// please do not edit this file
