<?php

namespace App\R4\Model;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Users extends genClass
{
    protected $use_table = "users";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "itemid" => ["type" => "float", "value" => null],
        "slkey" => ["type" => "str", "value" => null],
        "slname" => ["type" => "str", "value" => null],
        "buyfromboxkey" => ["type" => "str", "value" => null],
        "venderlanddetail" => ["type" => "str", "value" => null],
        "noticesent" => ["type" => "int", "value" => 6],
        "notes" => ["type" => "str", "value" => null],
        "expireunix" => ["type" => "int", "value" => 0],
        "packageid" => ["type" => "int", "value" => 0],
        "locktoreseller" => ["type" => "int", "value" => 0],
    ];
    public function getItemid(): ?float
    {
        return $this->getField("itemid");
    }
    public function getSlkey(): ?string
    {
        return $this->getField("slkey");
    }
    public function getSlname(): ?string
    {
        return $this->getField("slname");
    }
    public function getBuyfromboxkey(): ?string
    {
        return $this->getField("buyfromboxkey");
    }
    public function getVenderlanddetail(): ?string
    {
        return $this->getField("venderlanddetail");
    }
    public function getNoticesent(): ?int
    {
        return $this->getField("noticesent");
    }
    public function getNotes(): ?string
    {
        return $this->getField("notes");
    }
    public function getExpireunix(): ?int
    {
        return $this->getField("expireunix");
    }
    public function getPackageid(): ?int
    {
        return $this->getField("packageid");
    }
    public function getLocktoreseller(): ?int
    {
        return $this->getField("locktoreseller");
    }
    /**
    * setItemid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setItemid(?float $newvalue): array
    {
        return $this->updateField("itemid", $newvalue);
    }
    /**
    * setSlkey
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setSlkey(?string $newvalue): array
    {
        return $this->updateField("slkey", $newvalue);
    }
    /**
    * setSlname
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setSlname(?string $newvalue): array
    {
        return $this->updateField("slname", $newvalue);
    }
    /**
    * setBuyfromboxkey
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBuyfromboxkey(?string $newvalue): array
    {
        return $this->updateField("buyfromboxkey", $newvalue);
    }
    /**
    * setVenderlanddetail
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setVenderlanddetail(?string $newvalue): array
    {
        return $this->updateField("venderlanddetail", $newvalue);
    }
    /**
    * setNoticesent
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setNoticesent(?int $newvalue): array
    {
        return $this->updateField("noticesent", $newvalue);
    }
    /**
    * setNotes
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setNotes(?string $newvalue): array
    {
        return $this->updateField("notes", $newvalue);
    }
    /**
    * setExpireunix
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setExpireunix(?int $newvalue): array
    {
        return $this->updateField("expireunix", $newvalue);
    }
    /**
    * setPackageid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setPackageid(?int $newvalue): array
    {
        return $this->updateField("packageid", $newvalue);
    }
    /**
    * setLocktoreseller
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setLocktoreseller(?int $newvalue): array
    {
        return $this->updateField("locktoreseller", $newvalue);
    }
}
// please do not edit this file
