export default interface Interface_Package{
    id: number,
    packageUid: string,
    name: string,
    autodj: boolean,
    autodjSize: string,
    listeners: number,
    bitrate: number,
    templateLink: number,
    servertypeLink: number,
    cost: number,
    days: number,
    textureSoldout: string,
    textureInstockSmall: string,
    textureInstockSelected: string,
    welcomeNotecardLink: number,
    setupNotecardLink: number,
    enableGroupInvite: boolean,
    enforceCustomMaxStreams: boolean,
    maxStreamsInPackage: number
}
export const Default_Package: Interface_Package = {
    id: 0,
    packageUid: "",
    name: "",
    autodj: true,
    autodjSize: "",
    listeners: 0,
    bitrate: 0,
    templateLink: 0,
    servertypeLink: 0,
    cost: 0,
    days: 0,
    textureSoldout: "",
    textureInstockSmall: "",
    textureInstockSelected: "",
    welcomeNotecardLink: 0,
    setupNotecardLink: 0,
    enableGroupInvite: true,
    enforceCustomMaxStreams: true,
    maxStreamsInPackage: 0
}