<?php

namespace App;

use YAPF\DB_OBJECTS\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Botconfig extends genClass
{
    protected $use_table = "botconfig";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "avatarlink" => ["type" => "int", "value" => null],
        "secret" => ["type" => "str", "value" => null],
        "notecards" => ["type" => "bool", "value" => 0],
        "ims" => ["type" => "bool", "value" => 0],
    ];
    public function getAvatarlink(): ?int
    {
        return $this->getField("avatarlink");
    }
    public function getSecret(): ?string
    {
        return $this->getField("secret");
    }
    public function getNotecards(): ?bool
    {
        return $this->getField("notecards");
    }
    public function getIms(): ?bool
    {
        return $this->getField("ims");
    }
    public function setAvatarlink(?int $newvalue): array
    {
        return $this->updateField("avatarlink", $newvalue);
    }
    public function setSecret(?string $newvalue): array
    {
        return $this->updateField("secret", $newvalue);
    }
    public function setNotecards(?bool $newvalue): array
    {
        return $this->updateField("notecards", $newvalue);
    }
    public function setIms(?bool $newvalue): array
    {
        return $this->updateField("ims", $newvalue);
    }
}
// please do not edit this file
