<?php
	// Do not edit this file, rerun gen.php to update!
	class message_set extends collectionSet { }
	
	class message extends genClass
	{
		protected $use_table = "message";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"avatarlink" => array("type"=>"int","value"=>null),
			"message" => array("type"=>"str","value"=>null),
		);
		public function get_avatarlink() : ?int {  return $this->get_field("avatarlink");  } 
		public function get_message() : ?string {  return $this->get_field("message");  } 
		public function set_avatarlink(?int $newvalue) : array {  return $this->update_field("avatarlink",$newvalue);  } 
		public function set_message(?string $newvalue) : array {  return $this->update_field("message",$newvalue);  } 
	}
?>