<?php
	// Do not edit this file, rerun gen.php to update!
	class treevender_packages_set extends collectionSet { }
	
	class treevender_packages extends genClass
	{
		protected $use_table = "treevender_packages";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"treevenderlink" => array("type"=>"int","value"=>null),
			"packagelink" => array("type"=>"int","value"=>null),
		);
		public function get_treevenderlink() : ?int {  return $this->get_field("treevenderlink");  } 
		public function get_packagelink() : ?int {  return $this->get_field("packagelink");  } 
		public function set_treevenderlink(?int $newvalue) : array {  return $this->update_field("treevenderlink",$newvalue);  } 
		public function set_packagelink(?int $newvalue) : array {  return $this->update_field("packagelink",$newvalue);  } 
	}
?>