<?php
	// Do not edit this file, rerun gen.php to update!
	class botconfig_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?botconfig
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?botconfig
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?botconfig
		{
			return parent::get_first();
		}
	}
	
	class botconfig extends genClass
	{
		protected $use_table = "botconfig";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"avatarlink" => array("type"=>"int","value"=>null),
			"secret" => array("type"=>"str","value"=>null),
			"notecards" => array("type"=>"bool","value"=>0),
			"ims" => array("type"=>"bool","value"=>0),
		);
		public function get_id() : ?int {  return $this->get_field("id");  } 
		public function get_avatarlink() : ?int {  return $this->get_field("avatarlink");  } 
		public function get_secret() : ?string {  return $this->get_field("secret");  } 
		public function get_notecards() : ?bool {  return $this->get_field("notecards");  } 
		public function get_ims() : ?bool {  return $this->get_field("ims");  } 
		public function set_id(?int $newvalue) : array {  return $this->update_field("id",$newvalue);  } 
		public function set_avatarlink(?int $newvalue) : array {  return $this->update_field("avatarlink",$newvalue);  } 
		public function set_secret(?string $newvalue) : array {  return $this->update_field("secret",$newvalue);  } 
		public function set_notecards(?bool $newvalue) : array {  return $this->update_field("notecards",$newvalue);  } 
		public function set_ims(?bool $newvalue) : array {  return $this->update_field("ims",$newvalue);  } 
	}
?>