<?php
	// Do not edit this file, rerun gen.php to update!
	class detail_set extends collectionSet { }
	
	class detail extends genClass
	{
		protected $use_table = "detail";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"rentallink" => array("type"=>"int","value"=>null),
		);
		public function get_rentallink() : ?int {  return $this->get_field("rentallink");  } 
		public function set_rentallink(?int $newvalue) : array {  return $this->update_field("rentallink",$newvalue);  } 
	}
?>