<?php
	// Do not edit this file, rerun gen.php to update!
	class event_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?event
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?event
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?event
		{
			return parent::get_first();
		}
	}
	
	class event extends genClass
	{
		protected $use_table = "event";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"avatar_uuid" => array("type"=>"str","value"=>null),
			"avatar_name" => array("type"=>"str","value"=>null),
			"rental_uid" => array("type"=>"str","value"=>null),
			"package_uid" => array("type"=>"str","value"=>null),
			"event_new" => array("type"=>"bool","value"=>0),
			"event_renew" => array("type"=>"bool","value"=>0),
			"event_expire" => array("type"=>"bool","value"=>0),
			"event_remove" => array("type"=>"bool","value"=>0),
			"unixtime" => array("type"=>"int","value"=>null),
			"expire_unixtime" => array("type"=>"int","value"=>null),
			"port" => array("type"=>"int","value"=>0),
		);
		public function get_id() : ?int
		{
			return $this->get_field("id");
		}
		public function get_avatar_uuid() : ?string
		{
			return $this->get_field("avatar_uuid");
		}
		public function get_avatar_name() : ?string
		{
			return $this->get_field("avatar_name");
		}
		public function get_rental_uid() : ?string
		{
			return $this->get_field("rental_uid");
		}
		public function get_package_uid() : ?string
		{
			return $this->get_field("package_uid");
		}
		public function get_event_new() : ?bool
		{
			return $this->get_field("event_new");
		}
		public function get_event_renew() : ?bool
		{
			return $this->get_field("event_renew");
		}
		public function get_event_expire() : ?bool
		{
			return $this->get_field("event_expire");
		}
		public function get_event_remove() : ?bool
		{
			return $this->get_field("event_remove");
		}
		public function get_unixtime() : ?int
		{
			return $this->get_field("unixtime");
		}
		public function get_expire_unixtime() : ?int
		{
			return $this->get_field("expire_unixtime");
		}
		public function get_port() : ?int
		{
			return $this->get_field("port");
		}
	}
?>