<?php
	// Do not edit this file, rerun gen.php to update!
	class notecard_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?notecard
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?notecard
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?notecard
		{
			return parent::get_first();
		}
	}
	
	class notecard extends genClass
	{
		protected $use_table = "notecard";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"rentallink" => array("type"=>"int","value"=>null),
			"as_notice" => array("type"=>"bool","value"=>0),
			"noticelink" => array("type"=>"int","value"=>null),
		);
		public function get_id() : ?int {  return $this->get_field("id");  } 
		public function get_rentallink() : ?int {  return $this->get_field("rentallink");  } 
		public function get_as_notice() : ?bool {  return $this->get_field("as_notice");  } 
		public function get_noticelink() : ?int {  return $this->get_field("noticelink");  } 
		public function set_id(?int $newvalue) : array {  return $this->update_field("id",$newvalue);  } 
		public function set_rentallink(?int $newvalue) : array {  return $this->update_field("rentallink",$newvalue);  } 
		public function set_as_notice(?bool $newvalue) : array {  return $this->update_field("as_notice",$newvalue);  } 
		public function set_noticelink(?int $newvalue) : array {  return $this->update_field("noticelink",$newvalue);  } 
	}
?>