<?php
	// Do not edit this file, rerun gen.php to update!
	class textureconfig_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?textureconfig
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?textureconfig
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?textureconfig
		{
			return parent::get_first();
		}
	}
	
	class textureconfig extends genClass
	{
		protected $use_table = "textureconfig";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"name" => array("type"=>"str","value"=>null),
			"offline" => array("type"=>"str","value"=>null),
			"wait_owner" => array("type"=>"str","value"=>null),
			"stock_levels" => array("type"=>"str","value"=>null),
			"make_payment" => array("type"=>"str","value"=>null),
			"inuse" => array("type"=>"str","value"=>null),
			"renew_here" => array("type"=>"str","value"=>null),
			"treevend_waiting" => array("type"=>"str","value"=>null),
			"proxyrenew" => array("type"=>"str","value"=>null),
			"getting_details" => array("type"=>"str","value"=>null),
			"request_details" => array("type"=>"str","value"=>null),
		);
		public function get_id() : ?int
		{
			return $this->get_field("id");
		}
		public function get_name() : ?string
		{
			return $this->get_field("name");
		}
		public function get_offline() : ?string
		{
			return $this->get_field("offline");
		}
		public function get_wait_owner() : ?string
		{
			return $this->get_field("wait_owner");
		}
		public function get_stock_levels() : ?string
		{
			return $this->get_field("stock_levels");
		}
		public function get_make_payment() : ?string
		{
			return $this->get_field("make_payment");
		}
		public function get_inuse() : ?string
		{
			return $this->get_field("inuse");
		}
		public function get_renew_here() : ?string
		{
			return $this->get_field("renew_here");
		}
		public function get_treevend_waiting() : ?string
		{
			return $this->get_field("treevend_waiting");
		}
		public function get_proxyrenew() : ?string
		{
			return $this->get_field("proxyrenew");
		}
		public function get_getting_details() : ?string
		{
			return $this->get_field("getting_details");
		}
		public function get_request_details() : ?string
		{
			return $this->get_field("request_details");
		}
	}
?>