<?php
	// Do not edit this file, rerun gen.php to update!
	class transactions_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?transactions
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?transactions
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?transactions
		{
			return parent::get_first();
		}
	}
	
	class transactions extends genClass
	{
		protected $use_table = "transactions";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"avatarlink" => array("type"=>"int","value"=>null),
			"packagelink" => array("type"=>"int","value"=>null),
			"streamlink" => array("type"=>"int","value"=>null),
			"resellerlink" => array("type"=>"int","value"=>null),
			"regionlink" => array("type"=>"int","value"=>null),
			"amount" => array("type"=>"int","value"=>null),
			"unixtime" => array("type"=>"int","value"=>null),
			"transaction_uid" => array("type"=>"str","value"=>null),
		);
		public function get_id() : ?int
		{
			return $this->get_field("id");
		}
		public function get_avatarlink() : ?int
		{
			return $this->get_field("avatarlink");
		}
		public function get_packagelink() : ?int
		{
			return $this->get_field("packagelink");
		}
		public function get_streamlink() : ?int
		{
			return $this->get_field("streamlink");
		}
		public function get_resellerlink() : ?int
		{
			return $this->get_field("resellerlink");
		}
		public function get_regionlink() : ?int
		{
			return $this->get_field("regionlink");
		}
		public function get_amount() : ?int
		{
			return $this->get_field("amount");
		}
		public function get_unixtime() : ?int
		{
			return $this->get_field("unixtime");
		}
		public function get_transaction_uid() : ?string
		{
			return $this->get_field("transaction_uid");
		}
	}
?>