<?php
	// Do not edit this file, rerun gen.php to update!
	class treevender_packages_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?treevender_packages
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?treevender_packages
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?treevender_packages
		{
			return parent::get_first();
		}
	}
	
	class treevender_packages extends genClass
	{
		protected $use_table = "treevender_packages";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"treevenderlink" => array("type"=>"int","value"=>null),
			"packagelink" => array("type"=>"int","value"=>null),
		);
		public function get_id() : ?int
		{
			return $this->get_field("id");
		}
		public function get_treevenderlink() : ?int
		{
			return $this->get_field("treevenderlink");
		}
		public function get_packagelink() : ?int
		{
			return $this->get_field("packagelink");
		}
	}
?>