<?php
	// Do not edit this file, rerun gen.php to update!
	class actions_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?actions
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?actions
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?actions
		{
			return parent::get_first();
		}
	}
	
	class actions extends genClass
	{
		protected $use_table = "actions";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"actionneeded" => array("type"=>"str","value"=>null),
		);
		public function get_id() : ?int
		{
			return $this->get_field("id");
		}
		public function get_actionneeded() : ?string
		{
			return $this->get_field("actionneeded");
		}
	}
?>