<?php
	// Do not edit this file, rerun gen.php to update!
	class billing_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?billing
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?billing
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?billing
		{
			return parent::get_first();
		}
	}
	
	class billing extends genClass
	{
		protected $use_table = "billing";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"timeadj" => array("type"=>"float","value"=>0),
			"messages" => array("type"=>"float","value"=>0),
			"adjustments" => array("type"=>"int","value"=>0),
			"sentmessages" => array("type"=>"int","value"=>0),
		);
		public function get_id() : ?int
		{
			return $this->get_field("id");
		}
		public function get_timeadj() : ?double
		{
			return $this->get_field("timeadj");
		}
		public function get_messages() : ?double
		{
			return $this->get_field("messages");
		}
		public function get_adjustments() : ?int
		{
			return $this->get_field("adjustments");
		}
		public function get_sentmessages() : ?int
		{
			return $this->get_field("sentmessages");
		}
	}
?>