<?php
	// Do not edit this file, rerun gen.php to update!
	class r4_payments_pending_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?r4_payments_pending
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?r4_payments_pending
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?r4_payments_pending
		{
			return parent::get_first();
		}
	}

	class r4_payments_pending extends genClass
	{
		protected $use_table = "payments_pending";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"username" => array("type"=>"str","value"=>null),
			"useruuid" => array("type"=>"str","value"=>null),
			"amountpaid" => array("type"=>"int","value"=>null),
			"userid" => array("type"=>"str","value"=>null),
			"transactionID" => array("type"=>"str","value"=>null),
			"accepted" => array("type"=>"int","value"=>0),
			"acceptedhash" => array("type"=>"str","value"=>null),
		);
		public function get_id() : ?int
		{
			return $this->get_field("id");
		}
		public function get_username() : ?string
		{
			return $this->get_field("username");
		}
		public function get_useruuid() : ?string
		{
			return $this->get_field("useruuid");
		}
		public function get_amountpaid() : ?int
		{
			return $this->get_field("amountpaid");
		}
		public function get_userid() : ?string
		{
			return $this->get_field("userid");
		}
		public function get_transactionID() : ?string
		{
			return $this->get_field("transactionID");
		}
		public function get_accepted() : ?int
		{
			return $this->get_field("accepted");
		}
		public function get_acceptedhash() : ?string
		{
			return $this->get_field("acceptedhash");
		}
	}
?>
