<?php
	// Do not edit this file, rerun gen.php to update!
	class r4_reminder_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?r4_reminder
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?r4_reminder
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?r4_reminder
		{
			return parent::get_first();
		}
	}

	class r4_reminder extends genClass
	{
		protected $use_table = "reminder";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"SLkey" => array("type"=>"str","value"=>null),
			"SLname" => array("type"=>"str","value"=>null),
			"SLunixtime" => array("type"=>"str","value"=>null),
		);
		public function get_id() : ?int
		{
			return $this->get_field("id");
		}
		public function get_SLkey() : ?string
		{
			return $this->get_field("SLkey");
		}
		public function get_SLname() : ?string
		{
			return $this->get_field("SLname");
		}
		public function get_SLunixtime() : ?string
		{
			return $this->get_field("SLunixtime");
		}
	}
?>
