<?php
	// Do not edit this file, rerun gen.php to update!
	class r4_sales_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?r4_sales
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?r4_sales
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?r4_sales
		{
			return parent::get_first();
		}
	}

	class r4_sales extends genClass
	{
		protected $use_table = "sales";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"funds_new" => array("type"=>"float","value"=>null),
			"funds_renew" => array("type"=>"float","value"=>null),
			"tracking_new" => array("type"=>"int","value"=>null),
			"tracking_renew" => array("type"=>"int","value"=>null),
		);
		public function get_id() : ?int
		{
			return $this->get_field("id");
		}
		public function get_funds_new() : ?double
		{
			return $this->get_field("funds_new");
		}
		public function get_funds_renew() : ?double
		{
			return $this->get_field("funds_renew");
		}
		public function get_tracking_new() : ?int
		{
			return $this->get_field("tracking_new");
		}
		public function get_tracking_renew() : ?int
		{
			return $this->get_field("tracking_renew");
		}
	}
?>
