<?php
	// Do not edit this file, rerun gen.php to update!
	class r4_control_resellers_set extends collectionSet
	{
		public function get_object_by_field(string $fieldname,$value) : ?r4_control_resellers
		{
			return parent::get_object_by_field($fieldname,$value);
		}
		public function get_object_by_id($id=null) : ?r4_control_resellers
		{
			return parent::get_object_by_id($id);
		}
		public function get_first() : ?r4_control_resellers
		{
			return parent::get_first();
		}
	}

	class r4_control_resellers extends genClass
	{
		protected $use_table = "control_resellers";
		protected $dataset = array(
			"id" => array("type"=>"int","value"=>null),
			"userkey" => array("type"=>"str","value"=>null),
			"username" => array("type"=>"str","value"=>null),
			"accepted" => array("type"=>"int","value"=>0),
			"reseller_rate" => array("type"=>"int","value"=>0),
		);
		public function get_id() : ?int
		{
			return $this->get_field("id");
		}
		public function get_userkey() : ?string
		{
			return $this->get_field("userkey");
		}
		public function get_username() : ?string
		{
			return $this->get_field("username");
		}
		public function get_accepted() : ?int
		{
			return $this->get_field("accepted");
		}
		public function get_reseller_rate() : ?int
		{
			return $this->get_field("reseller_rate");
		}
	}
?>
