name: autobuild

on:
  push:
    tags:
    - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName
        with:
          tagRegexGroup: 1 # Optional. Default is 1.
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: madpeter/streamadmin:${{ steps.tagName.outputs.tag }}