<?php

namespace App\R4;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Bots extends genClass
{
    protected $use_table = "bots";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "bot_description" => ["type" => "str", "value" => null],
        "bot_enabled" => ["type" => "bool", "value" => 0],
        "bot_uuid" => ["type" => "str", "value" => null],
        "bot_key" => ["type" => "str", "value" => null],
        "bot_type" => ["type" => "str", "value" => null],
        "bot_invites" => ["type" => "int", "value" => 0],
        "bot_ims" => ["type" => "int", "value" => 0],
        "bot_notecards" => ["type" => "int", "value" => 0],
        "bot_im_before" => ["type" => "str", "value" => null],
        "bot_im_after" => ["type" => "str", "value" => null],
    ];
    public function getBot_description(): ?string
    {
        return $this->getField("bot_description");
    }
    public function getBot_enabled(): ?bool
    {
        return $this->getField("bot_enabled");
    }
    public function getBot_uuid(): ?string
    {
        return $this->getField("bot_uuid");
    }
    public function getBot_key(): ?string
    {
        return $this->getField("bot_key");
    }
    public function getBot_type(): ?string
    {
        return $this->getField("bot_type");
    }
    public function getBot_invites(): ?int
    {
        return $this->getField("bot_invites");
    }
    public function getBot_ims(): ?int
    {
        return $this->getField("bot_ims");
    }
    public function getBot_notecards(): ?int
    {
        return $this->getField("bot_notecards");
    }
    public function getBot_im_before(): ?string
    {
        return $this->getField("bot_im_before");
    }
    public function getBot_im_after(): ?string
    {
        return $this->getField("bot_im_after");
    }
    /**
    * setBot_description
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_description(?string $newvalue): array
    {
        return $this->updateField("bot_description", $newvalue);
    }
    /**
    * setBot_enabled
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_enabled(?bool $newvalue): array
    {
        return $this->updateField("bot_enabled", $newvalue);
    }
    /**
    * setBot_uuid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_uuid(?string $newvalue): array
    {
        return $this->updateField("bot_uuid", $newvalue);
    }
    /**
    * setBot_key
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_key(?string $newvalue): array
    {
        return $this->updateField("bot_key", $newvalue);
    }
    /**
    * setBot_type
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_type(?string $newvalue): array
    {
        return $this->updateField("bot_type", $newvalue);
    }
    /**
    * setBot_invites
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_invites(?int $newvalue): array
    {
        return $this->updateField("bot_invites", $newvalue);
    }
    /**
    * setBot_ims
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_ims(?int $newvalue): array
    {
        return $this->updateField("bot_ims", $newvalue);
    }
    /**
    * setBot_notecards
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_notecards(?int $newvalue): array
    {
        return $this->updateField("bot_notecards", $newvalue);
    }
    /**
    * setBot_im_before
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_im_before(?string $newvalue): array
    {
        return $this->updateField("bot_im_before", $newvalue);
    }
    /**
    * setBot_im_after
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_im_after(?string $newvalue): array
    {
        return $this->updateField("bot_im_after", $newvalue);
    }
}
// please do not edit this file
