<?php

namespace App\R4;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Messages_out extends genClass
{
    protected $use_table = "messages_out";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "username" => ["type" => "str", "value" => null],
        "userkey" => ["type" => "str", "value" => null],
        "message" => ["type" => "str", "value" => null],
        "notecard" => ["type" => "str", "value" => null],
        "object" => ["type" => "str", "value" => null],
        "landmark" => ["type" => "str", "value" => null],
        "datetime_sent" => ["type" => "str", "value" => null],
        "batchid" => ["type" => "int", "value" => null],
        "sys_op_sender" => ["type" => "str", "value" => null],
        "delay_send" => ["type" => "int", "value" => 1],
        "bot_command" => ["type" => "int", "value" => 0],
        "bot_magiccode" => ["type" => "str", "value" => null],
        "bot_type" => ["type" => "str", "value" => null],
    ];
    public function getUsername(): ?string
    {
        return $this->getField("username");
    }
    public function getUserkey(): ?string
    {
        return $this->getField("userkey");
    }
    public function getMessage(): ?string
    {
        return $this->getField("message");
    }
    public function getNotecard(): ?string
    {
        return $this->getField("notecard");
    }
    public function getObject(): ?string
    {
        return $this->getField("object");
    }
    public function getLandmark(): ?string
    {
        return $this->getField("landmark");
    }
    public function getDatetime_sent(): ?string
    {
        return $this->getField("datetime_sent");
    }
    public function getBatchid(): ?int
    {
        return $this->getField("batchid");
    }
    public function getSys_op_sender(): ?string
    {
        return $this->getField("sys_op_sender");
    }
    public function getDelay_send(): ?int
    {
        return $this->getField("delay_send");
    }
    public function getBot_command(): ?int
    {
        return $this->getField("bot_command");
    }
    public function getBot_magiccode(): ?string
    {
        return $this->getField("bot_magiccode");
    }
    public function getBot_type(): ?string
    {
        return $this->getField("bot_type");
    }
    /**
    * setUsername
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setUsername(?string $newvalue): array
    {
        return $this->updateField("username", $newvalue);
    }
    /**
    * setUserkey
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setUserkey(?string $newvalue): array
    {
        return $this->updateField("userkey", $newvalue);
    }
    /**
    * setMessage
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setMessage(?string $newvalue): array
    {
        return $this->updateField("message", $newvalue);
    }
    /**
    * setNotecard
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setNotecard(?string $newvalue): array
    {
        return $this->updateField("notecard", $newvalue);
    }
    /**
    * setObject
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setObject(?string $newvalue): array
    {
        return $this->updateField("object", $newvalue);
    }
    /**
    * setLandmark
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setLandmark(?string $newvalue): array
    {
        return $this->updateField("landmark", $newvalue);
    }
    /**
    * setDatetime_sent
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setDatetime_sent(?string $newvalue): array
    {
        return $this->updateField("datetime_sent", $newvalue);
    }
    /**
    * setBatchid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBatchid(?int $newvalue): array
    {
        return $this->updateField("batchid", $newvalue);
    }
    /**
    * setSys_op_sender
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setSys_op_sender(?string $newvalue): array
    {
        return $this->updateField("sys_op_sender", $newvalue);
    }
    /**
    * setDelay_send
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setDelay_send(?int $newvalue): array
    {
        return $this->updateField("delay_send", $newvalue);
    }
    /**
    * setBot_command
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_command(?int $newvalue): array
    {
        return $this->updateField("bot_command", $newvalue);
    }
    /**
    * setBot_magiccode
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_magiccode(?string $newvalue): array
    {
        return $this->updateField("bot_magiccode", $newvalue);
    }
    /**
    * setBot_type
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setBot_type(?string $newvalue): array
    {
        return $this->updateField("bot_type", $newvalue);
    }
}
// please do not edit this file
