<?php

namespace App\R4;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Payments_pending extends genClass
{
    protected $use_table = "payments_pending";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "username" => ["type" => "str", "value" => null],
        "useruuid" => ["type" => "str", "value" => null],
        "amountpaid" => ["type" => "int", "value" => null],
        "userid" => ["type" => "str", "value" => null],
        "transactionID" => ["type" => "str", "value" => null],
        "accepted" => ["type" => "int", "value" => 0],
        "acceptedhash" => ["type" => "str", "value" => null],
    ];
    public function getUsername(): ?string
    {
        return $this->getField("username");
    }
    public function getUseruuid(): ?string
    {
        return $this->getField("useruuid");
    }
    public function getAmountpaid(): ?int
    {
        return $this->getField("amountpaid");
    }
    public function getUserid(): ?string
    {
        return $this->getField("userid");
    }
    public function getTransactionID(): ?string
    {
        return $this->getField("transactionID");
    }
    public function getAccepted(): ?int
    {
        return $this->getField("accepted");
    }
    public function getAcceptedhash(): ?string
    {
        return $this->getField("acceptedhash");
    }
    /**
    * setUsername
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setUsername(?string $newvalue): array
    {
        return $this->updateField("username", $newvalue);
    }
    /**
    * setUseruuid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setUseruuid(?string $newvalue): array
    {
        return $this->updateField("useruuid", $newvalue);
    }
    /**
    * setAmountpaid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAmountpaid(?int $newvalue): array
    {
        return $this->updateField("amountpaid", $newvalue);
    }
    /**
    * setUserid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setUserid(?string $newvalue): array
    {
        return $this->updateField("userid", $newvalue);
    }
    /**
    * setTransactionID
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setTransactionID(?string $newvalue): array
    {
        return $this->updateField("transactionID", $newvalue);
    }
    /**
    * setAccepted
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAccepted(?int $newvalue): array
    {
        return $this->updateField("accepted", $newvalue);
    }
    /**
    * setAcceptedhash
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAcceptedhash(?string $newvalue): array
    {
        return $this->updateField("acceptedhash", $newvalue);
    }
}
// please do not edit this file
