<?php

namespace App\R7\Model;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Detail extends genClass
{
    protected $use_table = "detail";
    // Data Design
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "rentalLink" => ["type" => "int", "value" => null],
    ];
    // Getters
    public function getRentalLink(): ?int
    {
        return $this->getField("rentalLink");
    }
    // Setters
    /**
    * setRentalLink
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setRentalLink(?int $newvalue): array
    {
        return $this->updateField("rentalLink", $newvalue);
    }
    // Loaders
    public function loadByRentalLink(int $rentalLink): bool
    {
        return $this->loadByField("rentalLink", $rentalLink);
    }
}
// please do not edit this file
