<?php

namespace App\R7\Model;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Objects extends genClass
{
    protected $use_table = "objects";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "avatarLink" => ["type" => "int", "value" => null],
        "regionLink" => ["type" => "int", "value" => null],
        "objectUUID" => ["type" => "str", "value" => null],
        "objectName" => ["type" => "str", "value" => null],
        "objectMode" => ["type" => "str", "value" => null],
        "objectXYZ" => ["type" => "str", "value" => null],
        "lastSeen" => ["type" => "int", "value" => 0],
    ];
    public function getAvatarLink(): ?int
    {
        return $this->getField("avatarLink");
    }
    public function getRegionLink(): ?int
    {
        return $this->getField("regionLink");
    }
    public function getObjectUUID(): ?string
    {
        return $this->getField("objectUUID");
    }
    public function getObjectName(): ?string
    {
        return $this->getField("objectName");
    }
    public function getObjectMode(): ?string
    {
        return $this->getField("objectMode");
    }
    public function getObjectXYZ(): ?string
    {
        return $this->getField("objectXYZ");
    }
    public function getLastSeen(): ?int
    {
        return $this->getField("lastSeen");
    }
    /**
    * setAvatarLink
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAvatarLink(?int $newvalue): array
    {
        return $this->updateField("avatarLink", $newvalue);
    }
    /**
    * setRegionLink
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setRegionLink(?int $newvalue): array
    {
        return $this->updateField("regionLink", $newvalue);
    }
    /**
    * setObjectUUID
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setObjectUUID(?string $newvalue): array
    {
        return $this->updateField("objectUUID", $newvalue);
    }
    /**
    * setObjectName
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setObjectName(?string $newvalue): array
    {
        return $this->updateField("objectName", $newvalue);
    }
    /**
    * setObjectMode
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setObjectMode(?string $newvalue): array
    {
        return $this->updateField("objectMode", $newvalue);
    }
    /**
    * setObjectXYZ
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setObjectXYZ(?string $newvalue): array
    {
        return $this->updateField("objectXYZ", $newvalue);
    }
    /**
    * setLastSeen
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setLastSeen(?int $newvalue): array
    {
        return $this->updateField("lastSeen", $newvalue);
    }
}
// please do not edit this file
