<?php

namespace App\R7\Model;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Reseller extends genClass
{
    protected $use_table = "reseller";
    // Data Design
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "avatarLink" => ["type" => "int", "value" => null],
        "allowed" => ["type" => "bool", "value" => 0],
        "rate" => ["type" => "int", "value" => 0],
    ];
    // Getters
    public function getAvatarLink(): ?int
    {
        return $this->getField("avatarLink");
    }
    public function getAllowed(): ?bool
    {
        return $this->getField("allowed");
    }
    public function getRate(): ?int
    {
        return $this->getField("rate");
    }
    // Setters
    /**
    * setAvatarLink
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAvatarLink(?int $newvalue): array
    {
        return $this->updateField("avatarLink", $newvalue);
    }
    /**
    * setAllowed
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setAllowed(?bool $newvalue): array
    {
        return $this->updateField("allowed", $newvalue);
    }
    /**
    * setRate
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setRate(?int $newvalue): array
    {
        return $this->updateField("rate", $newvalue);
    }
    // Loaders
    public function loadByAvatarLink(int $avatarLink): bool
    {
        return $this->loadByField("avatarLink", $avatarLink);
    }
    public function loadByAllowed(bool $allowed): bool
    {
        return $this->loadByField("allowed", $allowed);
    }
    public function loadByRate(int $rate): bool
    {
        return $this->loadByField("rate", $rate);
    }
}
// please do not edit this file
