<?php
$view_reply->load_template(
    "full",
    "streamadminr5",
    array("full")
);
$view_reply->set_swap_tag_string("html_menu","");
$view_reply->set_swap_tag_string("page_title","");
$view_reply->set_swap_tag_string("page_actions","");
$view_reply->set_swap_tag_string("page_content","");
$view_reply->set_swap_tag_string("html_title","");
?>
