<?php

namespace App\Models;

use YAPF\Framework\DbObjects\GenClass\GenClass as GenClass;
use YAPF\Framework\Responses\DbObjects\UpdateReply as UpdateReply;
use YAPF\Framework\Responses\DbObjects\SingleLoadReply as SingleLoadReply;
use App\Models\Sets\ObjectsSet as ObjectsSet;
use App\Models\Sets\TransactionsSet as TransactionsSet;

// Do not edit this file, rerun gen.php to update!
class Region extends genClass
{
    protected $use_table = "region";
    // Data Design
    protected $fields = [
        "id",
        "name",
    ];
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "name" => ["type" => "str", "value" => null],
    ];
    // Setters
    /**
    * setName
    */
    public function setName(?string $newValue): UpdateReply
    {
        return $this->updateField("name", $newValue);
    }
    // Getters
    public function getName(): ?string
    {
        return $this->getField("name");
    }
    // Loaders
    public function loadByName(string $name): SingleLoadReply
    {
        return $this->loadByField(
            "name",
            $name
        );
    }
    public function relatedObjects(): ObjectsSet
    {
        $ids = [$this->getId()];
        $collection = new ObjectsSet();
        $collection->loadFromRegionLinks($ids);
        return $collection;
    }
    public function relatedTransactions(): TransactionsSet
    {
        $ids = [$this->getId()];
        $collection = new TransactionsSet();
        $collection->loadFromRegionLinks($ids);
        return $collection;
    }
}
// please do not edit this file
