<?php

namespace App\R7\Set;

use YAPF\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use App\R7\Model\Datatable as Datatable;

// Do not edit this file, rerun gen.php to update!
class DatatableSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\R7\Model\Datatable");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Datatable
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Datatable
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldname, $value): ?Datatable
    {
        return parent::getObjectByField($fieldname, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Datatable
    {
        return parent::current();
    }
    // Loaders
    /**
     * loadByHideColZero
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByHideColZero(
                    bool $hideColZero, 
                    int $limit = 0, 
                    string $orderBy = "id", 
                    string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField("hideColZero", $hideColZero, $limit, $orderBy, $orderDir);
    }
    /**
     * loadByCol
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByCol(
                    int $col, 
                    int $limit = 0, 
                    string $orderBy = "id", 
                    string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField("col", $col, $limit, $orderBy, $orderDir);
    }
    /**
     * loadByCols
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByCols(
                    string $cols, 
                    int $limit = 0, 
                    string $orderBy = "id", 
                    string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField("cols", $cols, $limit, $orderBy, $orderDir);
    }
    /**
     * loadByName
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByName(
                    string $name, 
                    int $limit = 0, 
                    string $orderBy = "id", 
                    string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField("name", $name, $limit, $orderBy, $orderDir);
    }
    /**
     * loadByDir
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByDir(
                    string $dir, 
                    int $limit = 0, 
                    string $orderBy = "id", 
                    string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField("dir", $dir, $limit, $orderBy, $orderDir);
    }
}
