<?php

namespace App\R7\Set;

use YAPF\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use App\R7\Model\Objects as Objects;

// Do not edit this file, rerun gen.php to update!
class ObjectsSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\R7\Model\Objects");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Objects
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Objects
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldname, $value): ?Objects
    {
        return parent::getObjectByField($fieldname, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Objects
    {
        return parent::current();
    }
    // Loaders
    /**
     * loadByAvatarLink
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByAvatarLink(
        int $avatarLink,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): array {
        return $this->loadByField("avatarLink", $avatarLink, $limit, $orderBy, $orderDir);
    }
    /**
     * loadByRegionLink
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByRegionLink(
        int $regionLink,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): array {
        return $this->loadByField("regionLink", $regionLink, $limit, $orderBy, $orderDir);
    }
    /**
     * loadByObjectUUID
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByObjectUUID(
        string $objectUUID,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): array {
        return $this->loadByField("objectUUID", $objectUUID, $limit, $orderBy, $orderDir);
    }
    /**
     * loadByObjectName
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByObjectName(
        string $objectName,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): array {
        return $this->loadByField("objectName", $objectName, $limit, $orderBy, $orderDir);
    }
    /**
     * loadByObjectMode
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByObjectMode(
        string $objectMode,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): array {
        return $this->loadByField("objectMode", $objectMode, $limit, $orderBy, $orderDir);
    }
    /**
     * loadByObjectXYZ
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByObjectXYZ(
        string $objectXYZ,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): array {
        return $this->loadByField("objectXYZ", $objectXYZ, $limit, $orderBy, $orderDir);
    }
    /**
     * loadByLastSeen
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByLastSeen(
        int $lastSeen,
        int $limit = 0,
        string $orderBy = "id",
        string $orderDir = "DESC"
    ): array {
        return $this->loadByField("lastSeen", $lastSeen, $limit, $orderBy, $orderDir);
    }
}
