<?php

namespace App\R7\Set;

use YAPF\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use App\R7\Model\Timezones as Timezones;

// Do not edit this file, rerun gen.php to update!
class TimezonesSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("App\R7\Model\Timezones");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Timezones
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Timezones
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldname, $value): ?Timezones
    {
        return parent::getObjectByField($fieldname, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Timezones
    {
        return parent::current();
    }
    // Loaders
    /**
     * loadByName
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByName(
                    string $name, 
                    int $limit = 0, 
                    string $orderBy = "id", 
                    string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField("name", $name, $limit, $orderBy, $orderDir);
    }
    /**
     * loadByCode
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByCode(
                    string $code, 
                    int $limit = 0, 
                    string $orderBy = "id", 
                    string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField("code", $code, $limit, $orderBy, $orderDir);
    }
}
